### ISSUE TITLE
Better support for anaconda virtualenvs

### ISSUE THREAD

**Issue by cpaulik** [yyuu/pyenv-virtualenv#103]
See the discussion in https://github.com/yyuu/pyenv/issues/467 for reference

**Comment by yyuu** [comment]
Opened some of PRs to improve interoperability to Anaconda/Miniconda. As a side effect, I believe this would also sophisticate the handling of virtual environments created by virtualenv/pyvenv.

* #104
* #106
* #107 
* yyuu/pyenv#471

**Comment by thomasjo** [comment]
@yyuu Please let me know if there's anything specific I can help out with regards to testing these changes :bow:

**Comment by cpaulik** [comment]
@yyuu Thanks, This looks like a very good set of changes.

**Comment by yyuu** [comment]
I'd like to ask you guys to test with your environments including 3rd party tools for interoperability. I'll update this once I wrote missing tests and merge them into `master` branch....

**Comment by yyuu** [comment]
I've finished merging all of them. Please give it a try, and let me know if there is a problem.

**Comment by cpaulik** [comment]
I've tested all the things that gave me problems before and they work like a charm now. Thanks a lot :heart:

**Comment by cpaulik** [comment]
I've found one problem that might bite some users.

running `source activate testenv` does not work as it would in anaconda but closes the console

Would it be possible to make the `activate` shim behave like the activate script of anaconda?

Normally I would of course use `pyenv activate` but I ran into this because of a script that uses `source activate` to activate an environment. Which means that setup scripts which work everywhere break if a user has `pyenv` installed.

**Comment by yyuu** [comment]
Umm. It's difficult to hook the invocation of `source activate` in pyenv.... I'm trying to look for some workaround for it, but none of working code is ready for now.

This would be a issue living with Anaconda/Miniconda, but it must not be a new issue introduced by the PRs.

**Comment by yyuu** [comment]
Fortunately there is pyenv-virtualenv-init. Manipulating PATH in it might be working for the issue. I don't like to do such thing in pyenv, but I haven't yet found any other solutions. Basically I really hate installing source scripts in PATH :disappointed:

**Comment by yyuu** [comment]
Opened a PR for `source activate` issue.

https://github.com/yyuu/pyenv-virtualenv/pull/108

**Comment by cpaulik** [comment]
@yyuu Thanks for considering it. I can understand your aversion to installing source scripts in PATH. I tested the PR and it works as expected. Also activating an environment using `source` and deactivating it with `pyenv deactivate` works as expected.

**Comment by yyuu** [comment]
Is there still something need to be done?

**Comment by cpaulik** [comment]
After a day of testing this works very well now. Thank you.
