### ISSUE TITLE
Handle multiple versions better: check for single venv / activate first/only venv

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv-virtualenv#105]
If there are several Python versions being used, e.g. through `PYENV_VERSION=venv:system`, pyenv-virtualenv aborts with:

> pyenv-virtualenv: cannot activate multiple versions at once: venv system

I think it should be changed:
a) only abort in case there are multiple virtualenvs, e.g. by looking for the activate scripts in them
b) use the first/only virtualenv from the list with `activate`.

**Comment by yyuu** [comment]
Hm, b sounds reasonable.

**Comment by yyuu** [comment]
Modifying virtualenv-init to support multiple versions seems to be way hard.... I'd need some more time for preparing working patch :(
