### ISSUE TITLE
Unclear about which virtualenv to set as local

### ISSUE THREAD

**Issue by jagmoreira** [yyuu/pyenv-virtualenv#113]
I upgraded pyenv to 20151105 and pyenv-virtualenv to 20151103 and now every time I create a new virtual environment it appears in 2 places:

```
$ pyenv versions
  system
  2.7.10
  2.7.10/envs/venv
  3.5.0
  3.5.0/envs/general
* venv (set by <local folder>/.python-version)
  general

$ pyenv virtualenvs
  2.7.10/envs/venv (created from <home folder>/.pyenv/versions/2.7.10)
  3.5.0/envs/general (created from <home folder>/.pyenv/versions/3.5.0)
  general (created from <home folder>/.pyenv/versions/3.5.0)
* venv (created from <home folder>/.pyenv/versions/2.7.10)
```
As you can see I set the virtual environment in with `pyenv local venv`.

I didn't think too much about it but then I started seeing these whenever I used IPython (installed through `pip`):
```
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
```
However if I instead do `pyenv local 2.7.10/envs/venv`, the message goes away.

Why is that?
Should I always use the "long name" of the virtualenv whenever I set it as a local pyenv version?

**Comment by yyuu** [comment]
It must be an problem of IPython. Basically you should ask why to IPython guys.

**Comment by blueyed** [comment]
btw: I've created a PR to address this in ipython a while back: https://github.com/ipython/ipython/pull/5939

**Comment by jagmoreira** [comment]
Ah. I searched for this in the ipython repo but couldn't find any recent issues/PRs.
Thanks @blueyed.

Anyways, after a73817e this shouldn't be a problem any more.
