### ISSUE TITLE
virtualenv issues: `venv' is marked deactivated. Need to use --force option. Why?

### ISSUE THREAD

**Issue by YAmikep** [yyuu/pyenv-virtualenv#114]
**1) Using the pyenv virtualenv wrapper**
Why do I get this message when trying to activate a virtual env after creating it?
```pyenv-virtualenv: 'venv' is marked deactivated. use 'pyenv activate --force venv' to activate forcibly'.```

```
vagrant@dev:~$ pyenv versions
  system
* 2.7.10 (set by PYENV_VERSION environment variable)
vagrant@dev:~$ pyenv virtualenv 2.7.10 venv
New python executable in /home/vagrant/.pyenv/versions/2.7.10/envs/venv/bin/python2.7
Also creating executable in /home/vagrant/.pyenv/versions/2.7.10/envs/venv/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/vagrant/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /home/vagrant/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages
vagrant@dev:~$ pyenv activate venv
pyenv-virtualenv: `venv' is marked deactivated. use `pyenv activate --force venv' to activate forcibly.
vagrant@dev:~$ pyenv activate --force venv
pyenv-virtualenv: activate venv
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(venv) vagrant@dev:~$ pyenb which python
```

**2) Using virtualenv directly**
I tried to use `virtualenv` directly instead of using the pyenv wrapper but why do I get this message `pyenv-virtualenv: deactivate venv2` when trying to activate it the virtualenv way?
Can we use virtualenv normally?

```
vagrant@dev:~$ pyenv shell 2.7.10
vagrant@dev:~$ pyenv versions
  system
* 2.7.10 (set by PYENV_VERSION environment variable)
vagrant@dev:~$ virtualenv venv2
New python executable in venv2/bin/python2.7
Also creating executable in venv2/bin/python
Installing setuptools, pip, wheel...done.
vagrant@dev:~$ source venv2/bin/activate
pyenv-virtualenv: deactivate venv2
(venv2)vagrant@dev:~$ 
```

Thanks

**Comment by yyuu** [comment]
1. pyenv-virtualenv persists deactivated version in `PYENV_DEACTIVATE` to prevent it to be activated once after manual activation. Just use `--force` to activate it regardless of `PYENV_DEACTIVATE`.

2. It is kind of a bug at least unintended behaviour. I fixed it in 47feedc9347be88c3056809073ee631b7b86cb02

**Comment by YAmikep** [comment]
Thanks for the responses.

I'm not sure to understand what "deactivated" means since I just created the virtualenv in this case and I use the pyenv command?
```
pyenv virtualenv 2.7.10 venv
pyenv activate venv
```

**Comment by yyuu** [comment]
I suspect you have used the name of 'venv' before and it was in PYENV_DEACTIVATE. Try it again with newly created shell.

**Comment by YAmikep** [comment]
I made a test with a freshly built VM so no other virtualenvs were created before and it still does that (see below.)

```
vagrant@dev:~$ pyenv virtualenv venv
...
vagrant@dev:~$ pyenv activate venv
pyenv-virtualenv: activate venv
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(venv) vagrant@dev:~$ pyenv deactivate
pyenv-virtualenv: deactivate 2.7.10/envs/venv
vagrant@dev:~$ pyenv activate venv
pyenv-virtualenv: `venv' is marked deactivated. use `pyenv activate --force venv' to activate forcibly.
vagrant@dev:~$
```

Also, why are there two virtual envs listed (`2.7.10/envs/venv` and `venv`) when creating a virtualenv?
```
vagrant@dev:~$ pyenv versions
  system
* 2.7.10 (set by PYENV_VERSION environment variable)
  2.7.10/envs/venv
  venv
```

Thanks

**Comment by yyuu** [comment]
It is because you activated once then deactivated it. You just need to specify `--force` to re-activate the virtualenv if it already marked deactivated.

In that case, `venv` is a symlink prepared for backward compatibility. The _real_ name virtualenv is at `$(pyenv root)/versions/2.7.10/envs/venv` and you can use both of them to use the virtualenv.

**Comment by YAmikep** [comment]
Sorry, I'm not following. I understand the force option but with virtualenv, you can activate/deactivate a virtualenv as much as you want since the purpose is to work in a virtualenv and then exit and then go back, etc: `source venb/bin/activate` and `deactivate` 

Why is this behavior different in the pyenv context? What does deactivate mean then?

Thanks

**Comment by yyuu** [comment]
It's different impl. If you want something to change, read and write code.
