### ISSUE TITLE
Seems can't use like before since v20151006?

### ISSUE THREAD

**Issue by shajiquan** [yyuu/pyenv-virtualenv#115]
Seems can't use like source ~/.pyenv/versions/ENV_NAME/bin/activate?

**Comment by yyuu** [comment]
So what's your problem

**Comment by shajiquan** [comment]
Many of my projects are depends on `source ~/.pyenv/versions/ENV_NAME/bin/activate` but now it is not  available.

And I can't use `pyenv update` on many of my servers because this update will break all my workflows.

**Comment by shajiquan** [comment]
So, How to make it backward compatibility?

**Comment by yyuu** [comment]
caa5832b8ae2b323060d218d282f8ac3242b3d73 should mitigate the issue with `source ~/.pyenv/versions/ENV_NAME/bin/activate`. The changes in pyenv-virtualenv should not break pyenv-update, though.

**Comment by shajiquan** [comment]
Thank you, got the update. Let me try.

**Comment by shajiquan** [comment]
Another problem here:

cd ~/.pyenv/versions/

$ pyenv virtualenv 3.4.3 py342
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/me/.pyenv/versions/3.4.3/envs/py342/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /Users/me/.pyenv/versions/3.4.3/envs/py342/lib/python3.4/site-packages

$ source py342/bin/activate
(py342) ✔ ~/.pyenv/versions [master|✔]

$ pyenv activate py34
pyenv-virtualenv: virtualenv `/Users/me/.pyenv/versions/3.4.3/envs/py342' is already activated
(py342) ✔ ~/.pyenv/versions [master|✔]

$ source py34/bin/activate
(py34) ✔ ~/.pyenv/versions [master|✔]

The problem is that I can't activate `py34` by using command `pyenv activate py34` while I am using `py342` env, but can be activated with `souce` command.

Confused.

**Comment by yyuu** [comment]
So what is `py34`.... You should describe the detail of your environment. Please write up some shell script to reproduce your issue.

**Comment by shajiquan** [comment]
Ok, sorry.

## OS Env
- **OS** : OS X 10.11
- **Pyenv version**: latest from github.
- **Pyenv virtualenv version**: latest from github.

## Envs created by pyenv-virtualenv

```bash
cd ~/.pyenv/versions; ll |grep py3

drwxr-xr-x  7 me  staff   238B Nov 12 22:47 py3
lrwxr-xr-x  1 me  staff    42B Nov 16 10:37 py34 -> /Users/me/.pyenv/versions/3.4.3/envs/py34
lrwxr-xr-x  1 me  staff    43B Nov 16 10:39 py342 -> /Users/me/.pyenv/versions/3.4.3/envs/py342
drwxr-xr-x  8 me  staff   272B Nov 12 17:28 py35
```


## Problem reproduce

```
cd ~/.pyenv/versions/
```


### Activate an env via `source` command

```
~/.pyenv/versions $
source ~/.pyenv/versions/py3/bin/activate $
(py3) ~/.pyenv/versions $
```

success.

### Activate another env via `source` command

```
source ~/.pyenv/versions/py34/bin/activate $
(py34) ~/.pyenv/versions  $
```

success too.

### Activate the third env via `pyenv activate` command

```
pyenv activate py342 $
```

failed, the error is:

```
pyenv-virtualenv: virtualenv `/Users/me/.pyenv/versions/3.4.3/envs/py34' is already activated
```

and now, the env wasn't chaged.

```
(py34) ~/.pyenv/versions $
```

**Comment by yyuu** [comment]
After v20151103, the behaviour of `pyenv activate` has been changed slightly. It now stops activating virtualenv if there is some virtualenv already activated. To activate the virtualenv forcibly, please try using `pyenv activate --force py342`.

**Comment by shajiquan** [comment]
@yyuu Thanks.
