### ISSUE TITLE
Virtual_env path not present in $PATH

### ISSUE THREAD

**Issue by DanyC97** [yyuu/pyenv-virtualenv#117]
Hi,

given the following steps:

```
pyenv activate dani
pip install awscli
```
i would expect to be able while the virtualenv is activated to run `aws help` however that is not the case because 

```
VIRTUAL_ENV=/usr/local/opt/pyenv/versions/test_blessing_module
LSCOLORS=GxFxCxDxBxegedabagaced
MAGENTA=
PATH=/usr/local/opt/pyenv/plugins/pyenv-virtualenv/shims:/usr/local/opt/pyenv/libexec:/usr/local/opt/pyenv/plugins/python-build/bin:/usr/local/opt/pyenv/plugins/pyenv-virtualenv/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/bin/jamf:/usr/local/MacGPG2/bin
```
and the aws binary is located at 

`/usr/local/opt/pyenv/versions/test_blessing_module/bin/aws`

any thoughts @yyuu ?

Thanks

**Comment by yyuu** [comment]
It is expected bahaviour with latest master. We stopped using virtualenv's activate script from pyenv-virtualenv, and I also stopped manipulating PATH during activation.

This must not be a problem since pyenv's shims should be in PATH. This change is needed to handle virtualenv as a 1st class version in pyenv.

Did you have any specific problem with current behaviour?

**Comment by DanyC97** [comment]
@yyuu the problems as mentioned is that the `aws` command is not found and you can see in the above my PATH. 

P.S - after i closed the terminal and opened again it seems the aws is found it my path coming from the shims - i guess all this was caused because i had to run the rehash ?

**Comment by blueyed** [comment]
> had to run the rehash

Possibly, but it should not be necessary - I don't remember though currently.  `pyenv-rehash` at least should be run automatically for "pip install" (if successful) - although it should be done always maybe?!

btw: that's a lot of pyenv related PATH entries (but I have similar ones) - rather noisy.

 - /usr/local/opt/pyenv/plugins/pyenv-virtualenv/shims
 - /usr/local/opt/pyenv/libexec
 - /usr/local/opt/pyenv/plugins/python-build/bin
 - /usr/local/opt/pyenv/plugins/pyenv-virtualenv/bin
 - /usr/local/opt/pyenv/shims
 - /usr/local/opt/pyenv/bin

> the aws binary is located at /usr/local/opt/pyenv/versions/test_blessing_module/bin/aws

So you had probably another virtualenv activated when installing aws?!
You said to install it after `pyenv activate dani`.

Where is aws installed now?

**Comment by yyuu** [comment]
There is [a built-in hook](https://github.com/yyuu/pyenv/blob/9ca7de5b6c0f5b467c9a5a22471d6dc334684c52/pyenv.d/exec/pip-rehash.bash) in recent release of pyenv and you don't have o run `pyenv rehash` manually after `pip install` with it.

**Comment by yyuu** [comment]
> ```
> pyenv activate dani
> ( ... )
> VIRTUAL_ENV=/usr/local/opt/pyenv/versions/test_blessing_module
> ```

`VIRTUAL_ENV` should always point to the virtualenv's prefix which is currently activated. It should be `/usr/local/opt/pyenv/versions/dani` in this case. I'm not sure what was happening at that time, but it seems there is something wrong in activation related feature.

Please restart your shell (if you're using some terminal multiplexer, I'd recommend you to restart its parent shell as well) and check if the problem persists even after shell restart.

**Comment by DanyC97** [comment]
@yyuu don't use any multiplexer, only iterm . Restarted shell and everything works now
Thanks
