### ISSUE TITLE
"pyenv versions --skip-aliases" does not skip aliases

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv-virtualenv#126]
I've noticed this when writing https://github.com/yyuu/pyenv-virtualenv/issues/120#issuecomment-160237871.

**Comment by yyuu** [comment]
This is not an issue of pyenv-virtualenv.

**Comment by blueyed** [comment]
Thanks for fixing and sorry for mixing it up.

**Comment by DanyC97** [comment]
thank you too
