### ISSUE TITLE
How to create virtualenv without setuptools installed?

### ISSUE THREAD

**Issue by cdwilson** [yyuu/pyenv-virtualenv#127]
Is it possible to use pyenv-virtualenv to create a virtualenv without setuptools installed?  I tried the following, but it doesn't seem to work:

    $ pyenv virtualenv --no-setuptools 2.7.10 test-no-setuptools
    New python executable in /Users/chris/.anyenv/envs/pyenv/versions/2.7.10/envs/test-no-setuptools/bin/python2.7
    Also creating executable in /Users/chris/.anyenv/envs/pyenv/versions/2.7.10/envs/test-no-setuptools/bin/python
    Ignoring indexes: https://pypi.python.org/simple
    Collecting setuptools
    Collecting pip
    Installing collected packages: setuptools, pip
    Successfully installed pip-6.1.1 setuptools-15.2

**Comment by yyuu** [comment]
It is not possible at least for now since it tries to run `ensurepip` after the creation. What is your purpose to skip the installation of setuptools?

https://github.com/yyuu/pyenv-virtualenv/blob/cf7dea411dca932e8a0dc6930eb608863da91502/bin/pyenv-virtualenv#L500-L501

**Comment by cdwilson** [comment]
I need to test the installation of setuptools & pip in a virtualenv which does not have these installed already.  Would it be possible to add a way to disable `ensurepip` as an option?
