### ISSUE TITLE
Can't activate by source command again?

### ISSUE THREAD

**Issue by shajiquan** [yyuu/pyenv-virtualenv#128]
Can't activate an env by `source ~/.pyenv/versions/ENV_NAME/bin/activate` again, just like #115.

**Comment by yyuu** [comment]
If you want to activate virtualenv manually, remove 'pyenv virtualenv-init -' from shell profile.

**Comment by shajiquan** [comment]
Thanks，but it is more hard to use now.

**Comment by DanyC97** [comment]
i said the same thing ...oh well ...

**Comment by yyuu** [comment]
Just saying something won't solve anything. Write patch and send PR if you need something.
