### ISSUE TITLE
How to rename a virtualenv ?

### ISSUE THREAD

**Issue by Insoleet** [yyuu/pyenv-virtualenv#129]
Do I have to delete and recreate it from scratch ?

**Comment by yyuu** [comment]
Basically renaming of virtualenv is dangerous. It'd be better recreating it.

**Comment by jeanspector** [comment]
You can just copy it:
`cpvirtualenv cirrent_name new_name`

**Comment by ned2** [comment]
In my experience copying/renaming virtualenvs breaks things.
