### ISSUE TITLE
pyenv activate/deactivate not working

### ISSUE THREAD

**Issue by carolyn-idi** [yyuu/pyenv-virtualenv#13]
I am having trouble activating a virtual environment with "pyenv activate".

I restarted my machine and am working in a fresh shell.
I have `pyenv` installed and it appears to be working correctly.

```
~ >> pyenv versions
  system
* 2.7.6 (set by /Users/insomniac/.pyenv/version)
  3.3.3
```

I create a new project and set the python version with pyenv:

```
>> mkdir myproj
>> cd myproj
myproj >> pyenv local 3.3.3
myproj >> pyenv local
3.3.3
```

I then create a virtualenv called "foo" and double check it was created

```
myproj >> pyenv virtualenv foo333

myproj >> pyenv virtualenvs
  foo333 (created from /Users/insomniac/.pyenv/versions/3.3.3)
```

If I list `pyenv versions`, it's showing in the list, so I assume the virtual environments are being saved in the same location (this is a bit confusing).

```
myproj >> pyenv versions
  system
  2.7.6
* 3.3.3 (set by /Users/insomniac/Repo/myproj/.python-version)
  foo333
```

If I try to active the "foo333" virtual environment for "myproject" I get the following error:

```
myproj >> pyenv activate foo333
pyenv: no such command `activate'
```

I restart my shell and try again with the same result:

```
myproj >> pyenv local
3.3.3
myproj >> pyenv virtualenvs
  foo333 (created from /Users/insomniac/.pyenv/versions/3.3.3)
myproj >> pyenv activate foo333
pyenv: no such command `activate'
myproj >> 
```

I am able to activate 'foo333' with the following command:

```
myproj >> source "$(pyenv prefix foo333)/bin/activate"
(foo333) myproj >>
```

If I try to deactivate - I can only use "deactivate" - I get the same error if I use pyenv deactivate

```
(foo333) myproj >> pyenv deactivate
pyenv: no such command `deactivate'

(foo333) myproj >> deactivate
myproj >> 
```

I installed pyenv-virtualenv this morning using "brew install".
Any ideas?

Thanks,
C.

**Comment by NathanDotTo** [comment]
Still something weird here. See below.

$brew install pyenv
==> Downloading https://homebrew.bintray.com/bottles/pyenv-1.2.8.mojave.bottle.tar.gz
Already downloaded: /Users/nsowatsk/Library/Caches/Homebrew/downloads/dff5316003f00a4b90aac3850d5a1324631d49a6d96719e2e7d2d4cf439c3561--pyenv-1.2.8.mojave.bottle.tar.gz
==> Pouring pyenv-1.2.8.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/1.2.8: 612 files, 2.4MB
$ pyenv --version
pyenv 1.2.8
$ pyenv commands
--version
commands
completions
exec
global
help
hooks
init
install
local
prefix
realpath.dylib
rehash
root
shell
shims
uninstall
version
version-file
version-file-read
version-file-write
version-name
version-origin
versions
whence
which

$ brew remove pyenv


$ brew install --HEAD pyenv-virtualenv
==> Installing dependencies for pyenv-virtualenv: pyenv
==> Installing pyenv-virtualenv dependency: pyenv
==> Downloading https://homebrew.bintray.com/bottles/pyenv-1.2.8.mojave.bottle.tar.gz
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/dff5316003f00a4b90aac3850d5a1324631d49a6d96719e2e7d2d4cf439c3561--pyenv-1.2.8.mojave.bottle.tar.gz
==> Pouring pyenv-1.2.8.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/1.2.8: 612 files, 2.4MB
==> Installing pyenv-virtualenv --HEAD
==> Cloning https://github.com/pyenv/pyenv-virtualenv.git
Updating /Users/xxx/Library/Caches/Homebrew/pyenv-virtualenv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 6d90f61 Merge pull request #290 from lmmarsano/fix-conda
==> ./install.sh
==> Caveats
To enable auto-activation add to your profile:
  if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
==> Summary
🍺  /usr/local/Cellar/pyenv-virtualenv/HEAD-6d90f61: 21 files, 62.8KB, built in 8 seconds
==> Caveats
==> pyenv-virtualenv
To enable auto-activation add to your profile:
  if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
$ pyenv commands
--version
activate
commands
completions
deactivate
exec
global
help
hooks
init
install
local
prefix
realpath.dylib
rehash
root
shell
shims
uninstall
version
version-file
version-file-read
version-file-write
version-name
version-origin
versions
virtualenv
virtualenv-delete
virtualenv-init
virtualenv-prefix
virtualenvs
whence
which


$pyenv activate <X> && python –version

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.

**Comment by david-ninox** [comment]
> OK - I'll give that a try.
> Thanks!

Did that work? I am getting a similar error

**Comment by lggwettmann** [comment]
Same here... how to solve this?

**Comment by sarojkmb** [comment]
Same issue for me

**Comment by bh4r4th** [comment]
`pyenv local your_virtual_env` creates a `.python-version` file in the file. Which made `pyenv deactivate` not to work for me. I simply deleted this `.python-version` file and used `pyenv deactivate your_virtual_env` to deactivate the env. 

Give it a try if it's same case.

**Comment by sparcbr** [comment]
$ pyenv deactivate aminhaquadra

Failed to deactivate virtualenv.                                                                                                      
                                                                                                                                      
Perhaps pyenv-virtualenv has not been loaded into your shell properly.                                                                
Please restart current shell and try again.

**Comment by smkbarbosa** [comment]
> $ pyenv deactivate aminhaquadra
> 
> Failed to deactivate virtualenv.
> 
> Perhaps pyenv-virtualenv has not been loaded into your shell properly. Please restart current shell and try again.


I solved this add in .bashrc:
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
