### ISSUE TITLE
Upgrade wheel with new virtualenvs

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv-virtualenv#133]
I've noticed that the `wheel` package is not up-to-date in a new virtualenv:

```
% pip install -U wheel
Collecting wheel
  Using cached wheel-0.26.0-py2.py3-none-any.whl
Installing collected packages: wheel
  Found existing installation: wheel 0.24.0
    Uninstalling wheel-0.24.0:
      Successfully uninstalled wheel-0.24.0
Successfully installed wheel-0.26.0
```

Since that might have a huge influence on if wheels are handled / built properly, it seems to be important to have up-to-date, and it should  be ensured in a new virtualenv.

**Comment by yyuu** [comment]
pyenv-virtualenv is just a wrapper of virtualenv. Provisioning of virtualenv could be a responsibility of `virtualenv`/`pyvenv` or underlying `ensurepip`.

Or, setting up some `after_virtualenv` hook might help you to upgrade some packages after creating virtualenv. Anyway basically I don't think it's not what we should do in pyenv-virtualenv itself.

**Comment by blueyed** [comment]
Yes, a `after_virtualenv` hook would work, but I think it should be provided by default - given its importance.

AFAIK `ensurepip` gets not used for e.g. 3.5.1 virtualenvs?

**Comment by yyuu** [comment]
Are you using 3.5.1 with pyvenv or virtualenv? Can you show me the output of `pyenv virtualenv --version`?

**Comment by yyuu** [comment]
It seems pyvenv doesn't care about `wheel`.

Unlike pyvenv, virtualenv will install `wheel` from its bundled `virtualenv_support`. Creating virtualenv with using older `virtualenv` package will install older `wheel`.

https://github.com/pypa/virtualenv/tree/develop/virtualenv_support

So, we'd have the following options:

1. Upgrade `virtualenv` anytime if update is available
  * I think this would be the best. I'm not sure how we can implement this, though.
2. Run `pip install -U wheel` after creating virtualenv
3. Do nothing - users should manage

**Comment by yyuu** [comment]
I reconsider about this but upgrading virtualenv implicitly would be way harmful. In my opinion, upgrading virtualenv (or, wheel only) shouldn't be the default behaviour at least.

**Comment by blueyed** [comment]
% PYENV_VERSION=3.5.1 pyenv virtualenv --version
pyenv-virtualenv 20151103 (pyvenv 3.5.1)

% pyenv virtualenv --version
pyenv-virtualenv 20151103 (virtualenv 13.1.2)

`/usr/bin/virtualenv` is from Arch Linux (python-virtualenv 13.1.2-2).

**Comment by blueyed** [comment]
I am using the system python most of the time / by default, since moving to Arch provides the latest Python already.

**Comment by yyuu** [comment]
Hmm.I suspect Arch's system virtualenv is little old.

**Comment by blueyed** [comment]
Seems to be the latest?! https://pypi.python.org/pypi/virtualenv/13.1.2

**Comment by yyuu** [comment]
Hmm, it seems that the wheel bundled with the latest virtualenv 13.1.2 is still wheel 0.24.0. Upgrading virtualenv could not be a solution.

https://github.com/pypa/virtualenv/tree/13.1.2/virtualenv_support

If stale wheel is an issue, it'd be better to fix virtualenv itself.

**Comment by blueyed** [comment]
Seems to be on track for virtualenv 13.2.0 (https://github.com/pypa/virtualenv/commit/49d741812dc15feac4d5b3ff88eed8cf8c00eab5).

Closing this as a non-pyenv-virtualenv issue.

**Comment by blueyed** [comment]
I've pinged Donald: https://twitter.com/blueyed/status/678012527100493824 - the last release is really old already after all.
