### ISSUE TITLE
activate no longer lists virtualenvs

### ISSUE THREAD

**Issue by cfblaeb** [yyuu/pyenv-virtualenv#134]
Hi, thanks for a great tool for using python,

After updating pyenv today, pyenv activate no longer sees any of my virtualenvs.
It worked before the update.

EDIT: I just noticed that virtualenvs made based on python 3.5.1 shows up (albeit twice, once as the name and once as 3.5.1/envs/name), but not virtualenvs based on pypy-4.0.1. 
All of them show up in pyenv uninstall.

I'm on ubuntu 15.10.

Also, it used to be that when I pressed tab after writing part of the name "pyenv" it would tab-complete to 1 space after pyenv (i.e. "pyenv ") after which I could e.g. type a<tab> and get "activate". Now all the plugin bins make tab-completion stop right after the v in "pyenv". Slight annoyance.

**Comment by yyuu** [comment]
Please post a gist from output of 'PYENV_DEBUG=1 pyenv virtualenv-prefix ${nane_of_the_virtualenv_created_from_pypy}' for debugging.

**Comment by yyuu** [comment]
@cfblaeb I realized that there is a bug in handling virtualenvs created by PyPy and Jython. I fixed it in 2d73d058bda606a3ec921545c838c1f6442f7256. Please give it a try and check if your problem has been solved. Feel free to reopen the issue if some issue persists.

**Comment by cfblaeb** [comment]
Fixed

**Comment by yyuu** [comment]
:relieved:
