### ISSUE TITLE
Explicitly state how to activate a virtualenv for newbies

### ISSUE THREAD

**Issue by evansendra** [yyuu/pyenv-virtualenv#141]
The README hints around this a lot, but there seems to be no line stating

    $ pyenv shell myenv

is the way to activate existing virtualenvs in the current directory.  This would have been helpful when switching over to pyenv virtualenv.

**Comment by evansendra** [comment]
actually there's one line that does it:

    $ pyenv shell venv27

but that's under (list existing virtualenvs)[$ pyenv shell venv27]

**Comment by yyuu** [comment]
RTFM. If you need more, send PRs.

https://github.com/yyuu/pyenv-virtualenv#activate-virtualenv
