### ISSUE TITLE
adding paths to PYTHONPATH on a per-virtualenv basis

### ISSUE THREAD

**Issue by toogy** [yyuu/pyenv-virtualenv#144]
I need to add a path to my PYTHONPATH environment variable but I want it to be added only inside a virtualenv. What is the cleanest way to do this?

**Comment by yyuu** [comment]
Basically I'd not recommend you to set custom `PYTHONPATH` because it may cause inconsistency with activated Python version in pyenv.

If you really need the functionality, I'd recommend you to use other tool like https://github.com/direnv/direnv. It allows you to define some environment variables inside specific directory.

**Comment by midnightradio** [comment]
Basically I agree what @yyuu said, but sometimes it is needed to set PYTHONPATH implicitly along with using default library path set by pyenv. How about providing a command to give a current PYTHONPATH according to the python version set by pyenv. Then we can use it without specifiying any virtual directory like PYTHONPATH=`pyenv pythonpath`/some-externals

**Comment by smdabdoub** [comment]
I would definitely be interested in this for python development work. I would love to be able to set up a virtual environment that has all the supporting libraries I need while at the same time having the pythonpath/path pointing to the git folder for my software.

**Comment by toogy** [comment]
@smdabdoub I wanted it for the exact same reason

**Comment by Larz60p** [comment]
I would also like to see this. I set my. In VSCode editor, I set code-runner.executorMap json '"python": "$pythonPath $fullFileName", when I open a virtual environment, sometimes it works, and others not and I cannot figure out why. I have been fighting this for some time now.
If anyone has insight on this, I'm all ears.

**Comment by blueardour** [comment]
function needed +1 

Any update?

**Comment by tgy** [comment]
@blueardour virtualenv is deprecated. Use `python -m venv` instead. It's part of the standard library now. You can read about it here: https://docs.python.org/3/library/venv.html?highlight=venv

**Comment by hongyi-zhao** [comment]
@tgy No, python3's venv module can only perform a subset in functionality of virtualenv.

See virtualenv's official website for more info.

**Comment by vedal** [comment]
I am looking for a solution to set PYTHONPATH="." when choosing a venv for a folder with `pyenv local`. 
Is the solution suggested by @yyuu the suggested best practice for this, or has pyenv added an extra hook for this? I suppose a manual solution would be adding a `.pth` file with `PYTHONPATH="path/to/local"` for each venv/project, but it feels like there might be a better way.

**Comment by barnabywalters** [comment]
If this basic functionality which was previously handled by `venv/bin/activate` isn‘t within the scope of pyenv-virtualenv, I’m curious what people‘s pyenv-virtualenv workflows look like for actual development? Are you setting PYTHONPATH=. manually every time you cd into a different folder? Doesn‘t that negate the benefits of pyenv automatically activating/deactivating environments as you move around the filesystem? I feel like I‘m missing something here.

**Comment by native-api** [comment]
What's the use case for setting `PYTHONPATH`? Virtualenv's site-packages directory is supposed to provide everything an environment needs.
Heck, [they even tried to get rid of `.pth` files as unnecessary](https://github.com/python/cpython/issues/78125)!
