### ISSUE TITLE
Provide a single-app install with virtualenv

### ISSUE THREAD

**Issue by rtgibbons** [yyuu/pyenv-virtualenv#145]
I'm not sure the best way to describe this, but I think this project sums it up

https://github.com/mitsuhiko/pipsi

I'm not a Python dev, but I enjoy the rbenv, nodenv style of management, and thus, using pyenv. Currently I have a few tools that need different versions of utilities, and so I use virtualenv to manage the difference dependencies of each. But having to activate that environment before I run the command is annoying.

For right now, I'm using pyenv to select my python version, and then installing with `pipsi --home $(pyenv prefix)/envs --bin-dir $(pyenv root)/shims` This seems to work, `uninstall` works `list` works. 

I'm wondering , based on your experience if there are any issues with this - both from a general point of view, and from creating this functionality as a plugin into pyenv-virtualenv or side-effects with pyenv.

**Comment by blueyed** [comment]
I'm also using pipsi - without any special arguments.

I use `pipsi` from Arch Linux (which uses Python 2), and also have a `pipsi3` wrapper - probably installed manually.

**Comment by yyuu** [comment]
Basically I'd not recommend to install symlinks inside pyenv's `shims` directory because it may be deleted after invocation of `pyenv rehash`. Just specifying `--home` to `pipsi` might be sufficient.

**Comment by rtgibbons** [comment]
Thanks, for the record, switching versions did indeed overwrite them. I ended moving to to another to `~/.pyenv/bin` just to keep everything inside pyenv root
