### ISSUE TITLE
virtualenvs are listet twice

### ISSUE THREAD

**Issue by mhubig** [yyuu/pyenv-virtualenv#147]
Suddenly the virtualenvs I create with `pyenv virtualenv` are listed twice with `pyenv virtualenvs` and `pyenv versions` (see the `trimeweb-forms` venv). As you can see at the `gl2server` venv, which I created some time ago, this was not always the case ...

```bash
$ pyenv virtualenvs
  2.7.11/envs/trimeweb-forms (created from /usr/local/var/pyenv/versions/2.7.11)
  gl2server (created from /usr/local/var/pyenv/versions/3.5.0)
  trimeweb-forms (created from /usr/local/var/pyenv/versions/2.7.11)
$ pyenv versions
* system (set by /usr/local/var/pyenv/version)
  2.7.10
  2.7.11
  2.7.11/envs/trimeweb-forms
  3.5.0
  gl2server
  trimeweb-forms
```

**Comment by yyuu** [comment]
It's an expected behaviour. The shorter one is just a symlink for backward compatibility. You can just use any of them.

**Comment by marco-buttu** [comment]
If they are supposed to appear twice, then the documentation is wrong:

```bash
$ pyenv virtualenvs
  miniconda3-3.9.1 (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
  miniconda3-3.9.1/envs/myenv (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
* venv27 (created from /home/yyuu/.pyenv/versions/2.7.10)
  venv34 (created from /home/yyuu/.pyenv/versions/3.4.3)
```

I expect to see two items of both venv27 and venv34

**Comment by nkgm** [comment]
Is it possible to opt-out of the double listing?

**Comment by asherstrayhorn** [comment]
> Is it possible to opt-out of the double listing?

`--skip-envs`		- removes  `x.y.z/envs/env-name`-like (you still see current selected/local version indicated with "*")
`--skip-aliases`	- removes  `env-name`-like (you don't see current version)
