### ISSUE TITLE
Automatic local activation not working on Guake terminal emulator

### ISSUE THREAD

**Issue by oblitum** [yyuu/pyenv-virtualenv#152]
- pyenv is at a6f1f48
- pyenv-virtualenv is at 17ee6e72b638f2f3f896972ab259b2616fe397d5
- terminal is zsh
- terminal emulator is Guake
- Linux is up to date Archlinux
- Using tmux

Even after explicitly executing 

```
eval "$(pyenv init -)" 
eval "$(pyenv virtualenv-init -)" 
```

When I enter a directory with a local virtual environment set, it doesn't change virtualenv anymore, this used to work. I have to execute `pyenv activate <env>`, and when I do that one time, local activation/deactivation starts to work when changing dir in that terminal window.

**Comment by oblitum** [comment]
Also, `pyenv local` does return the correct local env, even if it's not being set when entering directory.

**Comment by yyuu** [comment]
pyenv needs "shims" script at the beginnig part of PATH to hook command executions. I suspect you have something in your PATH. Please review what's in it carefully.

**Comment by oblitum** [comment]
@yyuu Hi, I didn't know it needed to be at the start of the PATH, I've reordered all may PATH and have put pyenv stuff at the start, this is the result:

```
/home/francisco/.pyenv/plugins/pyenv-virtualenv/shims:/home/francisco/.pyenv/libexec:
/home/francisco/.pyenv/plugins/python-build/bin:/home/francisco/.pyenv/plugins/pyenv-virtualenv/bin:
/home/francisco/.pyenv/plugins/pyenv-update/bin:/home/francisco/.pyenv/plugins/pyenv-installer/bin:
/home/francisco/.pyenv/plugins/pyenv-doctor/bin:/home/francisco/.pyenv/shims:/usr/local/bin:/usr/local/sbin:
/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:
/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/francisco/.pyenv/bin:/home/francisco/.rbenv/bin:
/home/francisco/.nodenv/bin:/home/francisco/.multirust/toolchains/nightly/cargo/bin:/home/francisco/.go/bin:
/home/francisco/.local/bin:/opt/src/apple/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/bin:
/opt/src/apple/swift/build/Ninja-ReleaseAssert/lldb-linux-x86_64/bin
```

Still, this didn't produce any effect, I still have the same behavior.

**Comment by oblitum** [comment]
I've changed PATH to just have pyenv stuff mostly, still no result:

```
/home/francisco/.pyenv/plugins/pyenv-virtualenv/shims:/home/francisco/.pyenv/libexec:
/home/francisco/.pyenv/plugins/python-build/bin:/home/francisco/.pyenv/plugins/pyenv-virtualenv/bin:
/home/francisco/.pyenv/plugins/pyenv-update/bin:/home/francisco/.pyenv/plugins/pyenv-installer/bin:
/home/francisco/.pyenv/plugins/pyenv-doctor/bin:/home/francisco/.pyenv/shims:/usr/local/bin:/usr/local/sbin:
/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:
/usr/bin/vendor_perl:/usr/bin/core_perl:/home/francisco/.pyenv/bin
```

**Comment by oblitum** [comment]
After this, after manual activation, it's not deactivating automatically like I described before, I also have to deactivate it manually when exiting the directory tree with a local environment. I have no idea what's going on but behaviour is being very inconsistent.

**Comment by oblitum** [comment]
For reference, these are my plugins:

```
$ ls ~/.pyenv/plugins
pyenv-doctor  pyenv-installer  pyenv-update  pyenv-virtualenv  pyenv-which-ext  python-build
```

**Comment by yyuu** [comment]
Basically you don't have to manage PATH for pyenv because pyenv-init will manage PATH to add pyenv at the top of PATH. If there's some other setting after pyenv-init, it might obstacle pyenv, thpugh.

Anyway I couldn't find problems in your PATH configuration. I'd recommend you to try with minimul shell configurations to debug the problem.

**Comment by oblitum** [comment]
Thanks for the suggestions, I've tried it on bare bash and zsh, yes, it's working there. My current setup is based on [prezto](https://github.com/sorin-ionescu/prezto), and it has been working for a long time before I updated pyenv/pyenv-virtualenv and I rarely change anything relevant on `.zshrc`/etc, maybe pyenv-virtualenv became incompatible with prezto over the last changes for some reason. I'll have to check whether it's broken in a default prezto setup.

**Comment by oblitum** [comment]
I've figured out the issue, it's the Guake terminal emulator. I've been using it recently and never expected it to be the thing conflicting with pyenv hooks. This is quite weird. I have no issues on Gnome Terminal, working just like before on my setup.

**Comment by yyuu** [comment]
Please let me know if there's something which can be fixed in pyenv-virtualenv.
