### ISSUE TITLE
Manual activation fails

### ISSUE THREAD

**Issue by anko** [yyuu/pyenv-virtualenv#155]
The [install instructions](https://github.com/yyuu/pyenv-virtualenv#installing-as-a-pyenv-plugin)' optional step 2 involves adding the `eval "$(pyenv virtualenv-init -)"` line to `~/.bash_profile`.  The step being optional implies that I could also choose to activate virtualenvs _manually_ [like this](https://github.com/yyuu/pyenv-virtualenv#activate-virtualenv).

However, if I try it manually with the listed command, I get an error.

```
$ pyenv activate nameOfMyEnv

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

I guess the step is not optional after all?

**Comment by yyuu** [comment]
It's still optional. I suspect your shell isn't configured to run pyenv-init. Please review your shell configuration.

**Comment by anko** [comment]
Ah, I see. I still need `eval "$(pyenv init -)"`—it's only `eval "$(pyenv virtualenv-init -)"` that's optional.

Sorry about the confusion.
