### ISSUE TITLE
The doc does not describe the actual behavior of "pyenv virtualenvs"

### ISSUE THREAD

**Issue by marco-buttu** [yyuu/pyenv-virtualenv#157]
Looking at the documentation, the `pyenv virtualenvs` command lists the `venv27` and `venv34` only once:

```bash
$ pyenv virtualenvs
  miniconda3-3.9.1 (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
  miniconda3-3.9.1/envs/myenv (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
* venv27 (created from /home/yyuu/.pyenv/versions/2.7.10)
  venv34 (created from /home/yyuu/.pyenv/versions/3.4.3)
```

I expect to see two items of both `venv27` and `venv34`. That's why there are so many issues opened, like  #156 , #147 , #148 .

By the way, it is a very nice tool, and I am describing it in my Italian Python book. The only thing I do not like, is the virtualenvs listed twice :/

**Comment by yyuu** [comment]
#158
