### ISSUE TITLE
Is any option to match rbenv-default-gem feature?

### ISSUE THREAD

**Issue by DanyC97** [yyuu/pyenv-virtualenv#159]
HI,

While i started to play with rbenv i found a useful plugin https://github.com/rbenv/rbenv-default-gems .Is any plugin/ option to do the same with pyenv-virtualenv & pip ?

**Comment by yyuu** [comment]
AFAIK, there's no equivalent impl for pyenv.

**Comment by yyuu** [comment]
This isn't related to pyenv-virtualenv itself.
