### ISSUE TITLE
'nodeenv -p' exports do not activate with pyenv activate

### ISSUE THREAD

**Issue by katakumpo** [yyuu/pyenv-virtualenv#162]
Hi, i need nodeenv to use the path provided by pyenv virtualenv and it failed.
I install a a pyenv virtualenv, than pip install nodeenv, than nodeenv -p --prebuilt.
This adds nodeenv code at ~/.pyenv/versions/myenv/bin/activate, but this script never gets executed with pyenv activate myenv.
I finally found a place to just source it in pyenv-sh-activate, but this is a hack:
```
# virtualenv/pyvenv
case "${shell}" in
fish )
  cat <<EOS
setenv PYENV_VIRTUAL_ENV "${prefix}";
setenv VIRTUAL_ENV "${prefix}";
EOS
  ;;
* )
  cat <<EOS
export PYENV_VIRTUAL_ENV="${prefix}";
export VIRTUAL_ENV="${prefix}";
source \$PYENV_VIRTUAL_ENV/bin/activate \$PYENV_VERSION;
EOS
  ;;
esac
```
Maybe someone can help to come up with a better solution, or point me in the direction i missed.

**Comment by yyuu** [comment]
pyenv-virtualenv will never execute activate script anymore. It only configures environment variables as same as virtualenv's activate script is doing.

**Comment by katakumpo** [comment]
Do you have any suggestion how to use pyenv together with nodeenv properly or let pyenv setup something for node in its own way?

**Comment by katakumpo** [comment]
and btw...i wrote this is a hack...never intended to make sincere pull request..just showing the hack to maybe get a better solution figured out :)
