### ISSUE TITLE
Typo in bin/pyenv-sh-activate ?

### ISSUE THREAD

**Issue by shangsunset** [yyuu/pyenv-virtualenv#164]
I get a prompt every time when i activate a virtualenv says 'pyenv-virtualenv: prompt changing not work for fish' . Is it intended to be 'pyenv-virtualenv: prompt changing not working for fish.' ?

A side note: the prompt changing from oh-my-fish actually works.
thanks.

**Comment by yyuu** [comment]
haha. I am really bad at English writing.... PRs welcome~

**Comment by shangsunset** [comment]
PR submitted. Thanks for your work.
