### ISSUE TITLE
pyenv virtualenv lists duplicated virtualenv

### ISSUE THREAD

**Issue by BradRuderman** [yyuu/pyenv-virtualenv#166]
I am using Mac OS X 10.11.4, I installed pyenv and virtualenv via brew. I am noticing every time I create a virtualenv, it gets duplicated. Not sure if this is expected.

<img width="568" alt="1__bradruderman_brads-mbp_____zsh__and_issues_ _yyuu_pyenv-virtualenv" src="https://cloud.githubusercontent.com/assets/2366784/14134884/cab09ac6-f60e-11e5-801f-c695c17ede74.png">

**Comment by BradRuderman** [comment]
never mind I see it's just a symlink.

**Comment by caleb15** [comment]
Thanks @BradRuderman I was wondering about that! :)

That clears up that mystery.

```shell
[fifteen5-deploy] pyenv virtualenvs                                                                                                                 
  3.6.8/envs/deploy (created from /home/caleb/.pyenv/versions/3.6.8)
  deploy (created from /home/caleb/.pyenv/versions/3.6.8)

[fifteen5-deploy] ll $(pyenv root)/versions
total 4.0K
drwxr-xr-x 7 caleb caleb 4.0K Oct 21 17:59 3.6.8
lrwxrwxrwx 1 caleb caleb   45 Feb 18 17:17 deploy -> /home/caleb/.pyenv/versions/3.6.8/envs/deploy
```
