### ISSUE TITLE
Suppress "deactivate/activate foo" message

### ISSUE THREAD

**Issue by puhitaku** [yyuu/pyenv-virtualenv#168]
I recently installed pyenv-virtualenv and found that entering a directory which I set a local env with `pyenv local foo` makes "deactivate / activate foo" message.

I'm used to old behavior - pyenv says nothing without setting VERBOSE - so I feel it's terribly annoying.

I read related Issue #104 #110 and your commit bf7e9ba59afe5df24e21cf2e6100420dd3e8af89 .
AFAIK prompt changing functionality was restored and can be disabled with setting `PYENV_VIRTUALENV_DISABLE_PROMPT` but activate messages are not. In my opinion providing user a way to disable the message should be provided.

Please give me your opinion and if you like it I'll send you a PR. Thanks.

**Comment by yyuu** [comment]
Adding something like PYENV_VIRTUALENV_VERBOSE_ACTIVATE would be better.

**Comment by yyuu** [comment]
Or, use -v argument given to pyenv-virtualenv-init? Both should work at least. From consistency point of view, the former might be better.

**Comment by puhitaku** [comment]
`PYENV_VIRTUALENV_VERBOSE_ACTIVATE` sounds better. But it sounds like *not* showing activating messages will be the default behavior, while pyenv shows the messages by default recently.

I like quiet pyenv but am worrying about changing default behavior.

**Comment by yyuu** [comment]
IIRC, the verbosity in messaging didn't change recently. Or, I didn't intend to change the behaviour at that time, at least.

Basically I agree with you; show messages only if there's something wrong should be the default behaviour. Kind of "incompatibility" in behaviour is always a matter and what we should avoid. Although some "changes" in messaging must be allowed. I believe that "quiet by default" principle could be the way for every Unix tools.

**Comment by yyuu** [comment]
I believe this has been fixed by #169 and #171. Please let me know if there's something remaining.
