### ISSUE TITLE
Too much noise!

### ISSUE THREAD

**Issue by nikolay** [yyuu/pyenv-virtualenv#180]
After a certain version, `pyenv-virtualenv` became too noisy in the default behavior:
```
pyenv-virtualenv: deactivate
pyenv-virtualenv: activate venv
```
It always complains if you try to activate a virtualenv that's already active:
```
pyenv-virtualenv: version `venv' is already activated
```
Is there a quiet option at least? Also, why the `activate` message doesn't use quotes around the version and the `already activated` does?

**Comment by yyuu** [comment]
Your explanation explains nothing. If you're on master branch, setting `PYENV_VIRTUALENV_VERBOSE_ACTIVATE` could make the scrip quiet. RTFS.

https://github.com/yyuu/pyenv-virtualenv/blob/1488c3ed65695d35756f8b887ea770053a0aa38f/bin/pyenv-sh-activate#L137-L139

**Comment by nikolay** [comment]
@yyuu What I'm saying is that the message format is inconsistent and the high verbosity in most systems is not enabled by default - there are way too many settings to tweak and changes to watch between versions. This should be like virtualenv - only better.

**Comment by nikolay** [comment]
@yyuu For whatever reason, this actually never works. I don't set this variable anywhere, I don't enable verbosity, I unset the variable just in case, I pass the quiet flag, and it still shows those messages!
