### ISSUE TITLE
Specify alternate base prefix?

### ISSUE THREAD

**Issue by rnwolf** [yyuu/pyenv-virtualenv#182]
I have multiple versions of python installed.

─➤  pyenv versions  
  system
  2.7.11
  2.7.11/envs/python2.7.11
  2.7.12
  2.7.12/envs/py2.7.12
  3.5.1
  3.5.1/envs/letsencrypt_py351
  letsencrypt_py351
  py2.7.12
- python2.7.11 (set by PYENV_VERSION environment variable)
  system-2.7.11

I am trying to create a virtual environment that launches python2 by default when I run "python".
All I seem to be able to do is run a python3 interpreter.

╰─➤  pyenv virtualenvs
  2.7.11/envs/python2.7.11 (created from /home/rnwolf/.pyenv/versions/3.5.1)
  2.7.12/envs/py2.7.12 (created from /home/rnwolf/.pyenv/versions/3.5.1)
  3.5.1/envs/letsencrypt_py351 (created from /home/rnwolf/.pyenv/versions/3.5.1)
  letsencrypt_py351 (created from /home/rnwolf/.pyenv/versions/3.5.1)
  py2.7.12 (created from /home/rnwolf/.pyenv/versions/3.5.1)
- python2.7.11 (created from /home/rnwolf/.pyenv/versions/3.5.1)
  system-2.7.11 (created from /usr)

(python2.7.11) ╭─rnwolf@rnwolf-XPS-15-9530 ~  
╰─➤  pyenv shell system-2.7.11

(system-2.7.11) ╭─rnwolf@rnwolf-XPS-15-9530 ~  
╰─➤  pyenv virtualenv venv2711
Requirement already satisfied (use --upgrade to upgrade): virtualenv in ./.local/lib/python2.7/site-packages
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Using base prefix '/home/rnwolf/.pyenv/versions/3.5.1'
New python executable in /home/rnwolf/.pyenv/versions/system-2.7.11/envs/venv2711/bin/python3.5
Also creating executable in /home/rnwolf/.pyenv/versions/system-2.7.11/envs/venv2711/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/rnwolf/.pyenv/versions/system-2.7.11/envs/venv2711/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /home/rnwolf/.pyenv/versions/system-2.7.11/envs/venv2711/lib/python3.5/site-packages

So now when I run "Python" I get the version 3 not 2.

On the other hand If I do the following:

Create a working directory
In the working directory
we want to create a virtualenv for a specific version thats been installed by pyenv.

virtualenv -p /home/rnwolf/.pyenv/versions/2.7.12/bin/python2.7 my2712env

That's it, check the version:

. ./my2712env/bin/activate && python -V

shows the expected version of python.

Is it possible to specify an alternative to this? 
Using base prefix '/home/rnwolf/.pyenv/versions/3.5.1'
##

**Comment by ourobourbon** [comment]
Can't you just do `pyenv virtualenv 2.7.11 venv2711`?

**Comment by aiguofer** [comment]
I'm having trouble creating a python2 virtualenv off my system install (on Arch, where the default python is 3). I've tried various combinations of the command and none have worked.

**Comment by blueyed** [comment]
@aiguofer 
AFAIK pyenv only knows about "system" (which is `python`, and Python 3 in your case), but not `system2`, or `system3`.  /cc @yyuu 
However, if you would change the `/usr/bin/python` symlink (or create a `/usr/local/bin/python` pointing to Python 2, that might work.  But I do not recommend that really.
I am also using Arch and am happy with having the latest Python as `system` always, and use manually installed versions for Python 2.

**Comment by blueyed** [comment]
I think @gwerbin is right, and that @aiguofer is another issue - and probably a limitation of pyenv.
Closing.
