### ISSUE TITLE
setprojectdir virtualenvwrapper style

### ISSUE THREAD

**Issue by TurboTim** [yyuu/pyenv-virtualenv#183]
I love pyenv and pyenv-virtualenv, but the only thing I wish for is the optional auto-switching to a project directory when the env is activated, ala virtualenvwrapper.

Keep up the great work yyuu!

**Comment by yyuu** [comment]
Use direnv or some equivalent. Don't do everything with swiss army knife.

http://direnv.net/

**Comment by TurboTim** [comment]
Thanks for the point, direnv looks perfect

**Comment by blueyed** [comment]
How does direnv work in that case?
If I understand it correctly you want to `cd` somewhere after `pyenv activate foo`, no?

**Comment by TurboTim** [comment]
I could switch it around and `pyenv activate foo` after `cd` ing into the project directory

**Comment by yyuu** [comment]
Ah sorry I was misunderstanding. Anyway pyenv-virtualenv will never support the behaviour (to avoid complicated problems in users's shell).

**Comment by TurboTim** [comment]
Its fine direnv worked a treat, its actually better as cd-ing into the dir transparently changes the env whih is arguably more intuitive anyway.

Thanks
