### ISSUE TITLE
Python's pyvenv script deprecated

### ISSUE THREAD

**Issue by nicktimko** [yyuu/pyenv-virtualenv#184]
Python 3.6 loudly [deprecates the `pyvenv` script](https://docs.python.org/dev/whatsnew/3.6.html#deprecated-features) as it (in more chaotic, non-pyenv environments `:P`) can be ambiguous what version it's using. The replacement is to simply use `python -m venv`. 

> As an aside, it amusingly it says `pyenv` is deprecated:
> 
> ```
> ntimko@pine2 ~/C/lepton> pyenv virtualenv 3.6.0a2 lepton
> WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv`
> Ignoring indexes: https://pypi.python.org/simple
> ...
> ```
> 
> The source being:
> ```python
> executable = pathlib.Path(sys.executable or 'python3').name
> print('WARNING: the pyenv script is deprecated in favour of '
>      f'`{executable} -m venv`', file=sys.stderr)
> ```

The `venv` package was added to the stdlib in 3.3, so I think anywhere that calls out to `pyvenv` can simply be replaced by `python -m venv`. In [`pyenv-virtualenv`](https://github.com/yyuu/pyenv-virtualenv/blob/master/bin/pyenv-virtualenv), I'm not familiar enough with the Bash syntax to trace exactly the logic of `$USE_PYVENV`, but something that might be semantically similar to looking for the script could be `python -m venv -h >/dev/null 2>&1` then looking at the exit code.

**Comment by yyuu** [comment]
:( Anyway thanks letting me know....

**Comment by nicktimko** [comment]
The little script is slated for removal in 3.8, so checking if it exists in a given version's `bin` directory will work just fine for another couple years, so suppressing the warning should just be as straightforward as replacing `pyvenv` calls with `python -m venv`?
