### ISSUE TITLE
fish shell: Error while reading file .venv/bin/activate.fish

### ISSUE THREAD

**Issue by davvelsan** [yyuu/pyenv-virtualenv#191]
Using fish shell, activating the environment causes an interpreter error.

**Some info**
```
Python 3.5.2				# python --version
fish, version 2.3.1			# fish --version
Linux arch 4.7.6-1-ARCH		# uname -a
```

**Reproduce**
```
source .venv/bin/activate.fish
```
**Problem** (lines 58-59, ENV_DIR=.venv)
```
if test -n "$(.venv) "
        printf "%s%s%s" "$(.venv) " (set_color normal) (_old_fish_prompt)
        return
end
```

Note that the `$(.venv)` should be `(.venv)`.  From fish shell help:
```
$(...) is not supported. In fish, please use '(...)'.
```

**Comment by yyuu** [comment]
pyenv-virtualenv never uses activate script generated by virtualenv/venv/conda. The error caused by activate of venv 3.5.2 is totally irrerevant to this project. I think the issue is as same as https://bugs.python.org/issue26664
