### ISSUE TITLE
Need for pyenv-virtualenv shims folder in PATH

### ISSUE THREAD

**Issue by crahan** [yyuu/pyenv-virtualenv#193]
I just installed pyenv-virtualenv through Homebrew and added the `eval "$(pyenv virtualenv-init -)"` line to my `.bash_profile`. This adds, in the case of Homebrew, `/usr/local/Cellar/pyenv-virtualenv/1.0.0/shims` (containing activate and deactivate) to the user's PATH.

Is this required? As far as I was able to test, removing that shims folder from my PATH does not break the virtualenv auto-activate/deactivate feature and calling activate or deactivate manually just throws an error stating _'pyenv-virtualenv: deactivate must be sourced. Run 'source deactivate' instead of 'deactivate''_ anyway.

I'm trying to understand what the requirements are for being able to access activate/deactivate manually when auto-activating virtualenvs is enabled and if removing the pyenv-virtualenv shims folder from the PATH has any negative impact.

**Comment by yyuu** [comment]
It's prepared as a workaround for Anaconda/miniconda's activate executable. It's safe to remove pyenv-virtualenv's shims from your PATH unless you're using it.

**Comment by crahan** [comment]
Thank you very much for the quick response. All is clear now!
