### ISSUE TITLE
How to force placement of python binary in bin directory?

### ISSUE THREAD

**Issue by adobeDan** [yyuu/pyenv-virtualenv#194]
Because I use PyCharm, which uses Python binaries (not symlinks to binaries) to locate a Python environment, I need pyenv virtualenv to place a Python binary (or hard link to one) in the created bin directory, not just a symlink to one.  I am not quite sure how to force this to happen.  I suspect that it's related to whether virtualenv or venv is being used to create the environment, and I suspect that I can force that by setting the VIRTUALENV_VERSION variable.  Can you clear this up for me?

**Comment by DanyC97** [comment]
@adobeDan have you sorted somehow the issue as i have similar one and it drives me crazy

**Comment by adobeDan** [comment]
This was resolved as a [PyCharm issue](https://youtrack.jetbrains.com/issue/PY-21787) with a posted workaround.  So I no longer need this functionality, and I'm closing this issue.
