### ISSUE TITLE
pyenv: no such command `virtualenv-init'

### ISSUE THREAD

**Issue by shulhi** [yyuu/pyenv-virtualenv#25]
I had this line `eval "$(pyenv virtualenv-init -)"` in my `.zshrc`, and ran `source .zshrc` and received the above error. 

Am I missing anything?

**Comment by gaborbernat** [comment]
On debian I have this same issue :( Any ideas? Using latest :)

**Comment by shulhi** [comment]
@gaborbernat instead of setting it at system wide level /etc/profile.d/pyenv.sh, have you try setting it under `bashrc` or `zshrc` if you're using zsh.

**Comment by gaborbernat** [comment]
Need this for all users, so cannot do that :)

**Comment by suzaku** [comment]
Try this:

`git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv`

**Comment by shudal** [comment]
@suzaku  Thank you so much,i met that problem just now,i solved it successfully by using your command.

**Comment by shudal** [comment]
I solved this same problem through rebooting the command line.

**Comment by MLDVN** [comment]
@suzaku 2019 sents you the love man, wtf, i just didnt have the plugins directory slipped in the path, wtf

**Comment by cvphelps** [comment]
+1 for this. Running `exec "$SHELL"` was giving me the error `pyenv: no such command `virtualenv-init'`. Once I went into the .pyenv folder and moved the pyenv-virtualenv directory inside .pyenv/plugins it worked.

**Comment by norioumata** [comment]
@suzaku, your solution works for me! 👍

**Comment by NickRyanDev** [comment]
try this: 

`git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv`

and after this:

`exec "$SHELL"`

I had the same issue into Debian running in WSL
