### ISSUE TITLE
Pyenv deactivate not working

### ISSUE THREAD

**Issue by madgeekfiend** [yyuu/pyenv-virtualenv#32]
I am using Python 3.4.1 and installed pyenv manually and via homebrew on my Mac OSX running v 10.9.3. After creating a virtualenv and then activating it, which all works. I have a problem with deactivating. When I run 'pyenv deactivate' nothing happens and my shell still shows me as being in the virtualenv.

Any ideas to fix this? Thanks. If I do 'pyenv shell --unset' while in a virtualenv works to 'deactivate'.

Running pyenv deactivate in debug. Hiding my directory name from web scrapers. 

++ [pyenv:15] type -p greadlink readlink
++ [pyenv:15] head -1
- [pyenv:15] READLINK=/usr/bin/readlink
- [pyenv:16] '[' -z /usr/bin/readlink ']'
- [pyenv:21] unset GREP_OPTIONS
- [pyenv:41] '[' -z /Users/**HIDDEN**/.pyenv ']'
- [pyenv:44] PYENV_ROOT=/Users/**HIDDEN**/.pyenv
- [pyenv:46] export PYENV_ROOT
- [pyenv:48] '[' -z '' ']'
  ++ [pyenv:49] pwd
- [pyenv:49] PYENV_DIR=/Users/**HIDDEN**
- [pyenv:58] export PYENV_DIR
- [pyenv:61] shopt -s nullglob
  ++ [pyenv:63] abs_dirname /Users/**HIDDEN**/.pyenv/bin/pyenv
  +++ [pyenv:28] pwd
  ++ [pyenv:28] local cwd=/Users/**HIDDEN**
  ++ [pyenv:29] local path=/Users/**HIDDEN**/.pyenv/bin/pyenv
  ++ [pyenv:31] '[' -n /Users/**HIDDEN**/.pyenv/bin/pyenv ']'
  ++ [pyenv:32] cd /Users/**HIDDEN**/.pyenv/bin
  ++ [pyenv:33] local name=pyenv
  +++ [pyenv:34] resolve_link pyenv
  +++ [pyenv:24] /usr/bin/readlink pyenv
  ++ [pyenv:34] path=../libexec/pyenv
  ++ [pyenv:31] '[' -n ../libexec/pyenv ']'
  ++ [pyenv:32] cd ../libexec
  ++ [pyenv:33] local name=pyenv
  +++ [pyenv:34] resolve_link pyenv
  +++ [pyenv:24] /usr/bin/readlink pyenv
  +++ [pyenv:34] true
  ++ [pyenv:34] path=
  ++ [pyenv:31] '[' -n '' ']'
  ++ [pyenv:37] pwd
  ++ [pyenv:38] cd /Users/**HIDDEN**
- [pyenv:63] bin_path=/Users/**HIDDEN**/.pyenv/libexec
- [pyenv:64] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
- [pyenv:65] bin_path=/Users/**HIDDEN**/.pyenv/libexec:/Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin
- [pyenv:64] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
- [pyenv:65] bin_path=/Users/**HIDDEN**/.pyenv/libexec:/Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin:/Users/**HIDDEN**/.pyenv/plugins/python-build/bin
- [pyenv:67] export PATH=/Users/**HIDDEN**/.pyenv/libexec:/Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin:/Users/**HIDDEN**/.pyenv/plugins/python-build/bin:/Users/**HIDDEN**/.pyenv/versions/test/bin:/Users/**HIDDEN**/.pyenv/shims:/Users/**HIDDEN**/.pyenv/bin:/Users/**HIDDEN**/.rvm/gems/ruby-2.1.2/bin:/Users/**HIDDEN**/.rvm/gems/ruby-2.1.2@global/bin:/Users/**HIDDEN**/.rvm/rubies/ruby-2.1.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/**HIDDEN**/.rvm/bin
- [pyenv:67] PATH=/Users/**HIDDEN**/.pyenv/libexec:/Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin:/Users/**HIDDEN**/.pyenv/plugins/python-build/bin:/Users/**HIDDEN**/.pyenv/versions/test/bin:/Users/**HIDDEN**/.pyenv/shims:/Users/**HIDDEN**/.pyenv/bin:/Users/**HIDDEN**/.rvm/gems/ruby-2.1.2/bin:/Users/**HIDDEN**/.rvm/gems/ruby-2.1.2@global/bin:/Users/**HIDDEN**/.rvm/rubies/ruby-2.1.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/**HIDDEN**/.rvm/bin
- [pyenv:69] hook_path=:/Users/**HIDDEN**/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
- [pyenv:73] export PYENV_HOOK_PATH=:/Users/**HIDDEN**/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
- [pyenv:73] PYENV_HOOK_PATH=:/Users/**HIDDEN**/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
- [pyenv:75] shopt -u nullglob
- [pyenv:78] command=sh-deactivate
- [pyenv:79] case "$command" in
  ++ [pyenv:87] command -v pyenv-sh-deactivate
- [pyenv:87] command_path=/Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-deactivate
- [pyenv:88] '[' -z /Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-deactivate ']'
- [pyenv:93] shift 1
- [pyenv:94] exec /Users/**HIDDEN**/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-deactivate
  ++ [pyenv-sh-deactivate:12] basename bash
- [pyenv-sh-deactivate:12] shell=bash
- [pyenv-sh-deactivate:13] case "$shell" in
- [pyenv-sh-deactivate:15] echo 'declare -f deactivate 1>/dev/null 2>&1 && deactivate;'
- [pyenv-sh-deactivate:18] '[' -z 1 ']'

**Comment by sbhakat** [comment]
Seems quite similar issue however I have the following problem while deactivating pyenv

#Checking the version
```
pyenv versions
  system
  3.6.7
  3.6.7/envs/keras-test
* keras-test (set by /home/sbhakat/.python-version)
```
Then I progressed as mentioned above

```
env | grep PYENV
PYENV_ROOT=/home/sbhakat/.pyenv
PYENV_VIRTUALENV_INIT=1
PYENV_VIRTUAL_ENV=/home/sbhakat/.pyenv/versions/3.6.7/envs/keras-test
PYENV_SHELL=bash
```

Trying to deactivate like

```
pyenv sh-deactivate keras-test
unset PYENV_VIRTUAL_ENV;
unset VIRTUAL_ENV;
if [ -n "${_OLD_VIRTUAL_PATH}" ]; then
  export PATH="${_OLD_VIRTUAL_PATH}";
  unset _OLD_VIRTUAL_PATH;
fi;
if [ -n "${_OLD_VIRTUAL_PYTHONHOME}" ]; then
  export PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME}";
  unset _OLD_VIRTUAL_PYTHONHOME;
fi;
if [ -n "${_OLD_VIRTUAL_PS1}" ]; then
  export PS1="${_OLD_VIRTUAL_PS1}";
  unset _OLD_VIRTUAL_PS1;
fi;
if declare -f deactivate 1>/dev/null 2>&1; then
  unset -f deactivate;
fi;
```

I also hashed the following part in .bashrc however seems like it is not working any help?

#if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
#fi
