### ISSUE TITLE
pyenv-virtualenv initialisation failing.

### ISSUE THREAD

**Issue by nayefc** [yyuu/pyenv-virtualenv#36]
When running `$  eval "$(pyenv virtualenv-init -)"`, I always get this error message:

```
Failed to deactivate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

For some reason, I can still use it on the same shell I installed it in, but not any other shell. How do I load up pyenv-virtualenv properly? Note: I Installed it using Homebrew.

I just realised I have issues with my virtualenv:

``` bash
$ python
-bash: /Users/ncopty/.pyenv/versions/finprod/bin/python: No such file or directory
```

``` bash
$ ~/.virtualenvs/finprod/bin/python
Python 2.7.2 (default, Jul  2 2014, 14:30:17) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.34.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Which one is the correct one and why do I have two?

**Comment by trankimhieu** [comment]
Thanks @nayefc This bug take me 30m to solve

**Comment by aristiden7o** [comment]
My PR adds @nayefc's tip to README.

**Comment by ankitjain87** [comment]
I am getting the same error when I am trying to activate in fish shell, but working fine in bash.

When I am trying to activate using direct command activate.fish, I am getting this error - 

`The file '.pyenv/versions/my_project/bin/activate.fish' is not executable by this user`

How can I make it working in fish shell

**Comment by Githeo** [comment]
Same error as @ankitjain87 here.

**Comment by bradleyhurley** [comment]
@ankitjain87  and @Githeo If you haven't already given up I was able to get fish working by adding

`status --is-interactive; and source (pyenv init -|psub)`
`status --is-interactive; and source (pyenv virtualenv-init -|psub)`

If you installed pyenv-virtualenv using Homebrew.

To my fish config.
`~/.config/fish/config.fish`

**Comment by Githeo** [comment]
Thanks @bradleyhurley, it works!
I hope your trick will be included in the doc.

**Comment by bradleyhurley** [comment]
I opened a PR - https://github.com/pyenv/pyenv-virtualenv/pull/280

**Comment by geoidesic** [comment]
I'm still getting this issue. Any fix / work-around?

**Comment by imedmar** [comment]
I was having trouble activating virtual environments due to same error mentioned in the original post.
Adding the following to `.zshrc` worked for me.
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by brianjuhl** [comment]
@imedmar -- THANK YOU!!

**Comment by btphan95** [comment]
@nayefc Thank you!!!
