### ISSUE TITLE
Cannot properly uninstall virtualenv

### ISSUE THREAD

**Issue by matthieugrieger** [yyuu/pyenv-virtualenv#49]
Hi,

I have been messing around with this for a few minutes and I can't quite figure out what the issue is. So I made a virtualenv to test out `pyechonest` for my brother, and once I was done I went to delete the virtualenv. First I simply deleted the directory containing the virtualenv. I have done this in the past and it has worked fine.

Now I get spammed with the following messages every time I execute _any_ command in the terminal:

```
pyenv: version `echonest2' is not installed
pyenv: version `echonest2' not installed
pyenv: version `echonest2' is not installed
```

echonest2 is the name of the virtualenv that I created.

I have also tried using `pyenv uninstall echonest2` and that didn't seem to help either. The only way I can get these messages to stop showing up is to take the stuff related to `pyenv` out of my `.bashrc`. I have even tried completely uninstalling pyenv (by deleting the `.pyenv`) directory, and that still didn't solve it.

Hopefully this makes sense.

Thanks!

P.S. I am running Arch Linux if that makes any difference.

**Comment by j-bennet** [comment]
I have the same issue on OS X after `rm -rf ~/.pyenv/versions/{my-env-name}`.

**Comment by blueyed** [comment]
@j-bennet 
See https://github.com/yyuu/pyenv-virtualenv/commit/a64f19416394e0a57ee5c4eeb62eeb2f6a3456f1 - there might be dirs installed.

Are you using the latest pyenv-virtualenv?
Can you provide a test case / steps to reproduce it?
Is the env used somewhere as a local or shell version?

The `~/.pyenv/versions/{my-env-name}` typically nowadays will be a symlink only to the real version.

**Comment by j-bennet** [comment]
Latest. The env was used as local for a dir. I do not have `~/pyenv/versions/{version}/envs` directory. Searched for it, but no.

**Comment by blueyed** [comment]
So what are your symptoms regarding this issue?
What errors do you get and when?

If it happens on shell startup, you could try from an existing shell to run `env PYENV_DEBUG=1 $SHELL`, which would open a subshell, probably with debug info.  Then you can see where the error is coming from (search the output).

If that does not help, try `export PYENV_DEBUG=1` in an existing shell and then trigger it.

**Comment by blueyed** [comment]
Steps to reproduce this would be very useful, because then it could be fixed and added to the test suite.

**Comment by blueyed** [comment]
I've tried to reproduce it:

```sh
% pyenv virtualenv test-foo
% pyenv local test-foo
% rm -rf ~/.pyenv/versions/test-foo
```

I do not get any errors after that, also for a new shell in this dir, but `pyenv version` just says `pyenv: version `test-foo' is not installed ...`, and the same error happens when trying to run any command managed by pyenv.

`~/.pyenv/versions/test-foo` is not a symlink for me currently however, too.

**Comment by blueyed** [comment]
Anyway, you can use `pyenv version` to see where it is coming from.

**Comment by blueyed** [comment]
In @matthieugrieger it was probably still set in the shell env (`PYENV_VERSION`), and fixed itself with a new shell (where it was not set to a non-existent version).

**Comment by j-bennet** [comment]
The symptoms are:
* when I try to execute any pyenv command
* when I open a new shell
I see `pyenv: {my-deleted-version}' is not installed`, and command is not executed (the command was trying to create a new virtualenv; it was not created).

**Comment by matthieugrieger** [comment]
@blueyed: Yes, I believe that is what happened.

**Comment by j-bennet** [comment]
It's not set at all. `echo $PYENV_VERSION`: nothing is printed.

**Comment by blueyed** [comment]
@j-bennet 
In your case it would be a `.python-version` file.
What does `pyenv version` give you?

**Comment by j-bennet** [comment]
Steps to reproduce.

1. `mkdir ~/repos/boo`
2. `cd ~/repos/boo`

The following steps are all inside `boo`.

```
--- repos/boo » pyenv virtualenv boo
New python executable in /Users/irina/.pyenv/versions/boo/bin/python2.7
Also creating executable in /Users/irina/.pyenv/versions/boo/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/irina/.pyenv/versions/boo/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /Users/irina/.pyenv/versions/boo/lib/python2.7/site-packages

--- repos/boo » pyenv local boo
pyenv-virtualenv: activate boo

(boo)--- repos/boo » cat .python-version
boo

(boo)--- repos/boo » deactivate

--- repos/boo » pyenv version
boo (set by /Users/irina/repos/boo/.python-version)

--- repos/boo » rm -rf ~/.pyenv/versions/boo
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)

--- repos/boo » pyenv version
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)

--- repos/boo » pyenv uninstall boo                                                                                                                                                                         pyenv: version `boo' not installed
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)

--- repos/boo » pyenv virtualenv foo                                                                                                                                                                        pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)

--- repos/boo » pyenv versions                                                                                                                                                                              pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
  system
  2.7.10
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
```

**Comment by yyuu** [comment]
Umm. It seems I forgot to redirect stderr to /dev/null. Just doing so would stop pyenv-virtualenv to do spamming.

https://github.com/yyuu/pyenv-virtualenv/blob/b9951fa69c13b1dbde0708bd70d8f85d21fd9858/bin/pyenv-sh-activate#L64

**Comment by yyuu** [comment]
@matthieugrieger @j-bennet I believe that the spamming will be suppressed with 9414a6bb302e55007fd58d7bb42dd6c2e3a81388. Please give it a try.

**Comment by j-bennet** [comment]
@yyuu I installed pyenv with homebrew, how do I update it to get the fix?

**Comment by yyuu** [comment]
@j-bennet Just try upgrading in the standard manner of Homebrew. 'brew update && brew upgrade pyenv pyenv-virtualenv'.

**Comment by j-bennet** [comment]
Does not seem to help.

```
--- ~/src » cd ~/repos/boo
--- repos/boo » ll
--- repos/boo » pyenv versions
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
  system
  2.7.10
  wharfee
--- repos/boo » pyenv uninstall boo
pyenv: version `boo' not installed
--- repos/boo » pyenv virtualenv foo                                                                                                                                                                    1 ↵
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
--- repos/boo » pyenv versions                                                                                                                                                                          1 ↵
pyenv: version `boo' is not installed (set by /Users/irina/repos/boo/.python-version)
  system
  2.7.10
  wharfee
```

**Comment by j-bennet** [comment]
In fact, pyenv is even more chatty now:

```
(wharfee) --- src/wharfee ‹volume-commands› » ll
total 80
-rw-r--r--   1 irina  staff   2.7K Dec 20 12:21 README.md
pyenv-virtualenv: deactivate wharfee
pyenv-virtualenv: deactivate
pyenv-virtualenv: activate wharfee
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
```
