### ISSUE TITLE
Command for temporary environments

### ISSUE THREAD

**Issue by drslump** [yyuu/pyenv-virtualenv#5]
Some times we just want to try some library, it would be nice to have something along the lines of the following to easily create a disposable environment.

```
#!/bin/sh
# TODO: generate a unique name if none given
# TODO: allow to define a base environment
pyenv virtualenv "$1"

echo "Entering a new shell session with version '$1'"
echo "Press ctrl+d or exit to terminate it" 

export PYENV_VERSION="$1"
$SHELL

echo "Destroying temp version '$1'"
pyenv uninstall -f "$1"
```

**Comment by blueyed** [comment]
virtualenvwrapper has a `mktmpenv` command:

    mktmpenv () {
            typeset tmpenvname
            typeset RC
            tmpenvname=$("$VIRTUALENVWRAPPER_PYTHON" -c 'import uuid,sys; sys.stdout.write(uuid.uuid4()+"\n")' 2>/dev/null) 
            if [ -z "$tmpenvname" ]
            then
                    tmpenvname=$("$VIRTUALENVWRAPPER_PYTHON" -c 'import random,sys; sys.stdout.write(hex(random.getrandbits(64))[2:-1]+"\n")' 2>/dev/null) 
            fi
            tmpenvname="tmp-$tmpenvname" 
            mkvirtualenv "$@" "$tmpenvname"
            RC=$? 
            if [ $RC -ne 0 ]
            then
                    return $RC
            fi
            cdvirtualenv
            echo "This is a temporary environment. It will be deleted when you run 'deactivate'." | tee "$VIRTUAL_ENV/README.tmpenv"
            cat - >> "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_ENV_BIN_DIR/postdeactivate" <<EOF
    if [ -f "$VIRTUAL_ENV/README.tmpenv" ]
    then
        echo "Removing temporary environment:" $(basename "$VIRTUAL_ENV")
        rmvirtualenv $(basename "$VIRTUAL_ENV")
    fi
    EOF
    }

But it is too heavy by itself, when only used for this functionality.

@drslump
Have you created a plugin for this yet?

@yyuu
I think it would be a good fit for the pyenv-virtualenv plugin itself.
Otherwise you'll have a plugin that depends on another plugin (pyenv-virtualenv).

**Comment by blueyed** [comment]
Here is an improved version of a `mktmpenv` script:

    #!/bin/sh -e

    if [ -n "$1" ]; then
      pyenv_version="$1"
    else
      pyenv_version=$(pyenv version-name | sed 's/:.*//')
    fi
    if [ -n "$2" ]; then
      venv_name="$2"
    else
      venv_name=$(mktemp --dry-run -d tmp-${pyenv_version}-XXXXXX)
    fi

    pyenv virtualenv "${pyenv_version}" "${venv_name}"

    echo
    echo "Entering a new shell session with virtualenv '${venv_name}' (${pyenv_version})."
    echo "It will be removed when exiting (ctrl+d or 'exit')."

    export PYENV_VERSION="${venv_name}"
    $SHELL

    echo "Destroying temporary virtualenv '${venv_name}'."
    pyenv uninstall -f "${venv_name}"

**Comment by blueyed** [comment]
@yyuu 
Do you think this is useful to have with the `virtualenv` plugin itself?
Should there be a new command (e.g. `mktmpenv`, as with virtualenv-wrapper), or a switch (`--tmp`)?

I think having a switch for this would be good.

**Comment by brbsix** [comment]
@blueyed Thanks for the script. I adapted it into a Bash function:

    # Create a temporary pyenv virtualenv
    mktempenv(){
        pyenv_version=${1:-$(pyenv version-name)}
        venv_name=${2:-$(mktemp --dry-run -d "tmp-$pyenv_version-XXXXXX")}

        pyenv virtualenv "$pyenv_version" "$venv_name"

        echo
        echo "Entering a new shell session with virtualenv '$venv_name' ($pyenv_version)."
        echo "It will be removed upon exit (ctrl+d or 'exit')."

        PYENV_VERSION=$venv_name "$SHELL"

        echo "Destroying temporary virtualenv '$venv_name'."
        pyenv uninstall -f "$venv_name"
    }

https://gist.github.com/brbsix/d0543fb380a991fd2d857270f0a9c31e
