### ISSUE TITLE
"activate" command breaks fish-shell PS1

### ISSUE THREAD

**Issue by douglascamata** [yyuu/pyenv-virtualenv#51]
In my current [oh-my-fish](https://github.com/bpinto/oh-my-fish/) theme (numist) I type command in the second line, but when I activate my pyenv-virtualenv it breaks and goes back to the same line as the other info. Check the screenshot for details.

![image](https://cloud.githubusercontent.com/assets/159076/4745920/8ab6f1dc-5a41-11e4-89a0-05fbc45365e4.png)

**Comment by mrvkino** [comment]
I can confirm the behaviour with my own fish_prompt.fish. Here is an example with my own prompt (with extra new line) and the same example you did.

![virtualenv](https://cloud.githubusercontent.com/assets/279511/6995425/8f55fdd2-db15-11e4-9425-54c84e63a418.png)
![virtualenv2](https://cloud.githubusercontent.com/assets/279511/6995426/8f57f6e6-db15-11e4-9a40-7b460cd4720f.png)

I am using echo and echo -n and insert logic to determine the color or my ">" character. I run the latest fish, pyenv and virtualenv. I also have oh-my-fish, but only use it to load rbenv.

I commented the oh-my-fish commands in my config.fish, as a test, to prevent it from loading and the same thing was happening.

**Comment by yyuu** [comment]
This must not happen anymore since we stopped using virtualenv's 'activate' script in #104
