### ISSUE TITLE
How does the auto activation/ deactivation works?

### ISSUE THREAD

**Issue by DanyC97** [yyuu/pyenv-virtualenv#52]
I'm running Mac 10.9.5 and i did the installation as below:

```
brew install pyenv
eval "$(pyenv init -)" >> ~/.bashrc
brew install pyenv-virtualenv
eval "$(pyenv virtualenv-init -)" >> ~/.bashrc
```

The installation home is all under

```
pyenv versions
* system (set by /usr/local/opt/pyenv/version)
  3.4.2
  ra1

[dani@localhost in ~]# ll /usr/local/opt/pyenv*
lrwxr-xr-x  1 dani  admin    24B Oct 22 16:27 /usr/local/opt/pyenv -> ../Cellar/pyenv/20141012
lrwxr-xr-x  1 dani  admin    35B Oct 22 16:38 /usr/local/opt/pyenv-virtualenv -> ../Cellar/pyenv-virtualenv/20141012

```

I read the other issues - #47 , #48, #32 , #33 and i've followed the same steps as in #32 (i get this are the manual steps)

```
[dani@localhost in ~]# pyenv versions
* system (set by /usr/local/opt/pyenv/version)
  3.4.2
  ra1
[dani@localhost in ~]# python -V
Python 2.7.6
[dani@localhost in ~]# echo PYENV_ACTIVATED
PYENV_ACTIVATED
[dani@localhost in ~]# echo $PYENV_ACTIVATED

[dani@localhost in ~]# echo $PYENV_DEACTIVATED

[dani@localhost in ~]# echo $PYENV_VIRTUALENV_INIT
1
[dani@localhost in ~]# pyenv activate ra1
(ra1) [dani@localhost in ~]# python -V
Python 3.4.2
(ra1) [dani@localhost in ~]# echo $PYENV_ACTIVATED

(ra1) [dani@localhost in ~]# echo $PYENV_DEACTIVATED

(ra1) [dani@localhost in ~]# echo $PYENV_VERSION
ra1
(ra1) [dani@localhost in ~]# pyenv deactivate
[dani@localhost in ~]# echo $PYENV_VERSION
ra1
[dani@localhost in ~]# echo $PYENV_DEACTIVATED

[dani@localhost in ~]# echo $PYENV_ACTIVATED

[dani@localhost in ~]# pyenv version
ra1 (set by PYENV_VERSION environment variable)
[dani@localhost in ~]# pyenv versions
  system
  3.4.2
* ra1 (set by PYENV_VERSION environment variable)
[dani@localhost in ~]#

```

BUT because the above behavior, when i'm trying to uninstall the virtual env i get this error

```
[dani@localhost in ~]# pyenv uninstall ra1
pyenv: remove /usr/local/opt/pyenv/versions/ra1? y
[dani@localhost in ~]# pyenv versions
pyenv: version `ra1' is not installed
  system
  3.4.2
```

In #47 you mentioned,

_As you mentioned, PYENV_DEACTIVATED should not persist after automatically triggered deactivation. I'll try to fix it in #47._

hence my question: **_what is the working flow for the auto activation/ deactivation? Do i need to be inside the PYENV_ROOT in order for auto activation to kick in?**_

In addition to this issue, according to the README file, the pyenv-virtualenv should be registered as a plugin inside pyenv, is this a bug in the brew formula's installation?

```
[dani@localhost in ~]# ll /usr/local/opt/pyenv/plugins/
total 8
lrwxr-xr-x  1 dani  admin    61B Oct 22 16:27 python-build -> /usr/local/Cellar/pyenv/20141012/default-plugins/python-build
```

**Comment by DanyC97** [comment]
FYI before i upgraded to latest version (using ```git pull```), the prompt was working when the virtualenv was activated. 

After the upgrade to latest/ greatest my prompt is no longer shown after activation.

**Comment by yyuu** [comment]
It is expected behaviour after #104. Currently we're not depending `activate` script created by virtualenv and it will not change the users' shell prompt anymore.

**Comment by DanyC97** [comment]
@yyuu while i do understand the work done to get anaconda env work better i'd appreciate if you add back the prompt to signal is active - otherwise is a massive killer from user experience pov.

**Comment by yyuu** [comment]
Hm, okay. I understood your request. I might revert them at least for non-fish. (I don't want to revert it for `fish` since the original code had some problems with oh-my-fish, as far as I remember)

**Comment by DanyC97** [comment]
@yyuu or if you want you can add a flag which could be set in the .bashrc (same way you set auto activation) to behave as of now or the old way - i.e change prompt to reflect the virtualenv name 

Thanks!

P.S  - virtualenv project behavior does show/ change the prompt to reflect the activation

**Comment by yyuu** [comment]
Pushed 3152718bfd28a208709122842d34c1e53df5f690 to restore prompt for non-fish.

**Comment by DanyC97** [comment]
Awesome, it works as expected, thank you!

P.S - suggestion: if in the future you planning to remove the prompt (w/o any flag to enable) please make a big note in the readme, in this way we can hold the upgrade ;)
