### ISSUE TITLE
Pyenv virtualenv installing in different location than the PYENV_ROOT path

### ISSUE THREAD

**Issue by devdinu** [yyuu/pyenv-virtualenv#53]
I've already installed few virtualenvs (those virtualenvs are listed down when i check pyenv virtualenvs in /usr/local/opt/pyenv/versions)

In zshrc i've added these lines

``` Batchfile
export PYENV_ROOT="/usr/local/opt/pyenv"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

$PYENV_ROOT is available in shell

``` Batchfile
echo $PYENV_ROOT : /usr/local/opt/pyenv
```

But if i try to install new pyenv version and using it creating a new virtualenv, the installation goes in different folder (i guess default) ~/.pyenv

Because of that my new virtualenv is not available (in pyenv virtualenvs, hence i can't use it)
1. What is the issue? Why it's installing in other location than the pyenv_root?
2. Is it possible to tell pyenv virtualenv that virtualenvs are in 2 locations? (adding the current location?) or how to solve this?

**Comment by nicolasguelfi** [comment]
Hi,
A simple working solution for me was:
- create a folder "mypyenv" in my wished location
- copy the content of .pyenv to mypyenv
- delete .pyenv
- make a symbolic link names.pyenv that point to mypyenv

**Comment by danielfaustino** [comment]
Hi,
A simple working solution for me was:

-     create a folder in my wished location
-     move into just created
-     `pyenv local 'python-version'`
-     done

**Comment by danielfaustino** [comment]
Hi,
A simple solution for me was:
- create a folder in my desired location
- switch to the created folder
- `pyenv local  "python-version"`
- done
