### ISSUE TITLE
Post install package for every virtualenv created

### ISSUE THREAD

**Issue by DanyC97** [yyuu/pyenv-virtualenv#56]
Is it possible to have a post install hook so that every time a new virtualenv is created a package is installed too?

The use case is simple: i'd like - in the same way pip is installed - to have iPython installed automatically with every pyenv virtualenv created.

**Comment by robcowie** [comment]
@DanyC97 I'd also like to install a standard set of packages in new virtualenvs. Any chance you could post your hook file? I'm having issues getting it to work (specifically, how do I reference pip in the newly created virtualenv from the script?). Cheers.

**Comment by nayefc** [comment]
I am trying to do the same thing. Doing an `after_virtualenv 'echo hi'` works. However, when I try to pip install it doesn't really install anything. Basically, I want a set of packages to be installed with every virtualenv created. Is that possible?

**Comment by jawshooah** [comment]
@robcowie @nayefc Are you looking for something similar to [`rbenv-default-gems`](https://github.com/sstephenson/rbenv-default-gems), but for `pyenv`? If so, I'm thinking about writing a `pyenv-default-pips` plugin that should take care of this.

**Comment by robcowie** [comment]
I'm unfamiliar with that project but it certainly looks like what I want. If you start the project, let me know. Cheers.

**Comment by nayefc** [comment]
@jawshooah Yup exactly. For example, I need pylint and Jedi and jediepcserver installed for each virtualenv and I was hoping to automate that as part of the pyenv mode hooks.

**Comment by jawshooah** [comment]
Just forked `rbenv-default-gems`, working on it now.

**Comment by nayefc** [comment]
@jawshooah That would be amazing please keep me posted!

**Comment by jawshooah** [comment]
[Boom](https://github.com/jawshooah/pyenv-default-packages).

**Comment by robcowie** [comment]
You're a legend. I'll give it a go shortly and report back.

**Comment by nayefc** [comment]
@jawshooah I'm trying to modify this to do it as I create a virtualenv, not when I install a version. I changed after_install to after_virtualenv but I still can't see the packages when I do pip freeze. Any ideas how to do such a modification?

**Comment by jawshooah** [comment]
Ah, seems I misunderstood the problem. The plugin is meant to install default packages when you install a new Python version; I assumed that if you wanted default packages for virtualenvs, the simplest way to get them was to have default packages for the Python base.

The reason `after_virtualenv` doesn't work here is that the plugin itself runs as an `after_install` hook. I could add a duplicate of `default-packages.bash` to `etc/pyenv.d/virtualenv` and `sed 's/after_install/after_virtualenv/'`, but it may be better to just create a `pyenv-virtualenv-default-packages` plugin.

**Comment by jawshooah** [comment]
Turns out `pyenv-virtualenv` does not include packages in the base Python when creating a virtualenv, which is probably expected behavior, so my initial thinking was flawed from the start. I'll make the change.

**Comment by nayefc** [comment]
@jawshooah That's fine I can do it myself. How do I create a plugin that runs after a virtualenv is created? I don't see where in your code you explicitly make an "after_install" package except for saying "after_install" in the bash script.

**Comment by jawshooah** [comment]
Until I make the change upstream, you can just copy `etc/pyenv.d/install/default-packages.bash` to `etc/pyenv.d/virtualenv/` and change `after_install` to `after_virtualenv` and `PYENV_VERSION` to `VIRTUALENV_NAME` in the new file. Haven't tried it yet myself, but it should work.

**Comment by jawshooah** [comment]
I created an [issue](https://github.com/jawshooah/pyenv-default-packages/issues/1) for this on my repo if you'd like to continue the conversation over there.

**Comment by DandyDev** [comment]
For those coming here from Google that want to install and/or upgrade packages after creation of a new virtualenv, you can do so as follows:

Run the following commands:

```
mkdir -p "$(pyenv root)/pyenv.d/virtualenv" # this will create a directory to hold "hooks" for pyenv virtualenv
$EDITOR "$(pyenv root)/pyenv.d/virtualenv/after.bash" # open your favorite editor to edit a new hook script
```

In your newly opened editor add the following contents to after.bash:

```
after_virtualenv 'PYENV_VERSION="$VIRTUALENV_NAME" pyenv-exec pip install --upgrade pip setuptools wheel'
```

And you're done! Now any time you create a new virtualenv, it will upgrade pip, setuptools and wheel and/or install them.
If you want to install (for example) `jupyter` to each new virtualenv, you can just add it at the end of the above command
