### ISSUE TITLE
pydoc3 link to existing Python install

### ISSUE THREAD

**Issue by stagrovin** [yyuu/pyenv-virtualenv#57]
Not sure if I did something wrong, but seems that the venv environment lacks of the pydoc link to the installed pyenv Python version, i.e, it's calling the system default instance from within the virtualenv, instead of the installed pyenv version it depends on.

Happened with pyenv + virtualenv of 3.4.2 python version:

**Comment by yyuu** [comment]
`pyenv virtualenv` is just a wrapper of `virtualenv` and `pyvenv` (for 3.3+). Probably it's a issue of `pyvenv`.
