### ISSUE TITLE
`pyenv shell` reports `Error: did not expect more than one argument.`

### ISSUE THREAD

**Issue by xu-cheng** [yyuu/pyenv-virtualenv#65]
If I install `pyenv-virtualenv`, it will report error every time I switch python env.

```
$ pyenv shell anaconda3-2.1.0
pyenv-virtualenv: activate anaconda3-2.1.0
Error: did not expect more than one argument.
```

**Comment by yyuu** [comment]
Weird :disappointed:

The `anaconda3-2.1.0` must not be a virtualenv and it shouldn't be `activate` basically. The `pyenv-virtualenv` should check if the activating version is a `virtualenv` or not with using [pyenv-virtualenv-prefix](https://github.com/yyuu/pyenv-virtualenv/blob/0fe9aef635865115eed32a629382bde73e887dc5/bin/pyenv-sh-activate#L65). Please gist the output from `PYENV_DEBUG=1 pyenv virtualenv-prefix anaconda3-2.1.0` to help investigation.

It seems there is something going wrong in auto-activation feature of pyenv-virtualenv. If nothing helps, just removing `eval "$(pyenv virtualenv-init -)"` from your shell configuration may help.

**Comment by yyuu** [comment]
I confirmed there is `activate` script in the prefix of `anaconda3-2.1.0`. This leads `pyenv-virtualenv-prefix` to recognize `anaconda3-2.1.0` as a virtualenv.

Until I or someone else prepare a workaround for this, I'd recommend you to disable `eval "$(pyenv virtualenv-init -)"` if you're using `anaconda` :(

**Comment by xu-cheng** [comment]
This is the gist: https://gist.github.com/xu-cheng/9cec6e81760167ba4275

I will disable it then. Thanks for helping.

**Comment by yyuu** [comment]
I pushed 0fc9441f091051cb482b47ce01455ecd0d9dcca3 to `master` to avoid try activating Anaconda.

**Comment by xu-cheng** [comment]
Thanks, it fixes the problem. Hope you can tag a new version for pyenv-virtualenv. I can help to push it to homebrew.
