### ISSUE TITLE
Do not use virtualenv's (de)activate scripts?

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv-virtualenv#69]
There are several issues with the virtualenv's activate script, especially with its handling of `$PATH` (https://github.com/pypa/virtualenv/pull/722).

Since it's basically rather trivial for what it does, I think it would be a good idea for pyenv-virtualenv to not use it, but do the setup / restoring itself.

Other issues: https://github.com/pypa/virtualenv/pull/724, https://github.com/pypa/virtualenv/pull/723.

**Comment by yyuu** [comment]
Avoid using the `activate` script generated by virtualenv is possible. But I think that keep using vanilla virtualenv would be better for compatibility.
