### ISSUE TITLE
"Failed to activate virtualenv" when running activate virtualenv from /bin/sh

### ISSUE THREAD

**Issue by tony** [yyuu/pyenv-virtualenv#70]
I need to be able to activate a virtualenv from ``pyenv-virtualenv`` from a script. It can't be a plugin, I just want to run it as a normal command, the same way ``workon`` and ``source ~/path/to/virtualenv/bin/activate`` does.

https://github.com/tony/tmuxp-config/blob/master/python/bootstrap_env.sh#L118

The script above is meant to abstract activating virtualenv projects.  Inside the script ``pyenv virtualenvs`` works, sourcing a virtualenv outright works, running ``workon`` in virtualenv works, but ``pyenv activate <env>`` fails. Running ``pyenv activate hhi`` works perfect in the same shell.

```console
$ ./bootstrap_env.sh -c "echo wha"  myvirtualenv                                  
detected manager pyenv-virtualenv

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
                                                              
$ pyenv activate myvirtualenv                                                                       ⏎
(myvirtualenv)$
```

**Comment by tony** [comment]
Closing this. The issue is if I want bootstrap_env.sh to source the new environment too, I had to do ``./bootstrap_env.sh -c "echo wha"  myvirtualenv``.

**Comment by barrywhart** [comment]
@tony: I'm having the same problem. Can you explain your solution in more detail and how it could be applied to other scripts?

**Comment by Falkor** [comment]
yes, I try to use [`direnv`](https://direnv.net/) to enable automatically the appropriate virtualenv through a project directory`.envrc` and it fails. Reinvoking manually within the shell works. 

```bash
$> cat myproject/.python-v* 
2.7.14
toto
$> cat myproject/.envrc
# (rootdir)/.envrc : direnv configuration file
# see https://direnv.net/
pyversion=$(head .python-version)
pvenv=$(head     .python-virtualenv)

if [ -n "$(which pyenv-virtualenv)" ]; then
  pyenv virtualenv --force --quiet ${pyversion} ${pvenv}-${pyversion}
  # activate it
  pyenv activate ${pvenv}-${pyversion}
fi 
``` 
Now if I cd into the directory (after allowing the `.envrc`): 
```
$> cd myproject
direnv: loading .envrc
[...]
Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```
Yet activating it manually (or by sourcing the file) works
```
$> pyenv activate toto-2.7.14
```

**Comment by LyleScott** [comment]
I have this same issue. It works fine manually but from a script, it fails everytime when I do a `pyenv virtualenv` and then `pyenv activate`

**Comment by Jakkwj** [comment]
- you can activate ``myvirtualenv`` manually in a terminal by: ``pyenv activate myvirtualenv``
- but in shell , you should try this: ``source "$HOME/.pyenv/versions/myvirtualenv/bin/activate" ``

**Comment by mbugert** [comment]
> but in shell , you should try this: source "$HOME/.pyenv/versions/myvirtualenv/bin/activate" 

Bourne shell does not have a `source` command, one needs to use `.` instead. Either way, `. "$HOME/.pyenv/versions/myvirtualenv/bin/activate"` was the solution for me.
