### ISSUE TITLE
Option to override VIRTUALENV_PATH

### ISSUE THREAD

**Issue by chrisb3ll** [yyuu/pyenv-virtualenv#81]
I have a specific use case where virtualenv's will be created and stored on the filesystem outside of the default pyenv install path.

Would it be possible to allow for overriding VIRTUALENV_PATH in plugins/pyenv-virtualenv/bin/pyenv-virtualenv?

Thanks

**Comment by yyuu** [comment]
I'm not sure what you want to do with this. You can create virtualenvs with directly using 'virtualenv' (or 'pyvenv'). You cannot manage them with using pyenv, though.

**Comment by chrisb3ll** [comment]
Understood. I incorrectly assumed I had to use pyenv-virtualenv over virtualenv.

I'll close this ticket and the pull request.

Thank you
