### ISSUE TITLE
Error messages need to be improved.

### ISSUE THREAD

**Issue by coredumperror** [yyuu/pyenv-virtualenv#83]
Today I tried installing a Python 2.6-based virtualenv through pyenv for the first time. But when I typed `pyenv virtualenv 2.6.9 project_name`, I got this output:

```
Usage: pyenv virtualenv [-f|--force] [VIRTUALENV_OPTIONS] <version> <virtualenv-name>
       pyenv virtualenv --version
       pyenv virtualenv --help

  -f/--force       Install even if the version appears to be installed already
```

That tells me absolutely nothing about what's wrong with my inputs, so I spent several minutes faffing about with various attempted fixes. I eventually realized that my problem was that I hadn't run `pyenv install 2.6.9` yet. 

Making it clear *why* an invocation of `pyenv virtualenv` failed is essential user feedback, and I'd very much like to see it added as soon as possible.

**Comment by blueyed** [comment]
Agreed.

> I'd very much like to see it added as soon as possible

Do you feel like creating a PR for this?

**Comment by coredumperror** [comment]
I'm not familiar with the code at all. I wouldn't know where to start, and I don't really have the free time to learn.

**Comment by yyuu** [comment]
I don't really have no free time, too. lol

**Comment by yyuu** [comment]
Not enough human beings have enough time to write code. This is great free software, free as in free beer.

**Comment by blueyed** [comment]
Thanks, @yyuu! :cherries: 

@coredumperror 
It's often a good opportunity to give something back to a project, just by scratching your own itch.  It's often just a quick "grep" away..  however, thanks for your report anyway!
