### ISSUE TITLE
Any option to set the path of virtualenv?

### ISSUE THREAD

**Issue by rowend** [yyuu/pyenv-virtualenv#84]
Is there any option to set the path for virtualenv?
Have a nice day

**Comment by yyuu** [comment]
Basically `pyenv virtualenv` is just a wrapper around `virtualenv` or `pyvenv`. If you'd like to create your virtualenv outside from pyenv, you can use plain `virtualenv` instead of `pyenv virtualenv`.

**Comment by rowend** [comment]
Thank you. ñ-ñ
