### ISSUE TITLE
Adding Different PYENV_ROOT with existing PYENV_ROOT

### ISSUE THREAD

**Issue by dineshkumar-cse** [yyuu/pyenv-virtualenv#85]
Hi, i've been using default configuration `/usr/local/opt/pyenv` for installing pyenv virtualenv version VENV_NAME. But it installs in `/usr/local/var/lib/pyenv/versions`
But after a while i change the PYENV_ROOT to different path `~/.mypyenv`, so it installed the new VENVs in the new path.

I tried changing PYENV_ROOT back to /usr/local/opt/pyenv but still it install new venvs in new folder ~/.mypyenv and its not listed in pyenv virtualenvs.

* Is it possible to have both old and new (different folders) to have virtual environments. so while listing pyenv virtualenv it should have venvs in both folders.
* If not Whats the right way to relocate venvs?

**Comment by yyuu** [comment]
It is not possible to have multiple `PYENV_ROOT`.

I'm not sure what was happening then, but it seems your environment had some stale definition of `PYENV_ROOT` probably in _shims_ scripts. If so, running `pyenv rehash` after re-defining `PYENV_ROOT` will update the `PYENV_ROOT` configuration in _shims_ scripts. After that, you can move the virtualenv to new location. Although, basically I'd not recommend you to relocate created virtualenv if you didn't create it as `--relocatable`. I'd recommend you to recreate virtualenv in new location.
