### ISSUE TITLE
Configuration to automatically install packages on new env

### ISSUE THREAD

**Issue by rodfersou** [yyuu/pyenv-virtualenv#86]
Is there a way to automatically add a list of packages after virtualenv creation?

For example I always install `debug`, `konch` and `cookiecutter` package after virtualenv creation with pip

It could be a global config file or environment

**Comment by yyuu** [comment]
There's no such feature at least for now. I think it should be implemented aspyenv plugins, or custom pyenv hooks.

**Comment by jawshooah** [comment]
I have a plugin for exactly this use case: [pyenv-default-packages](https://github.com/jawshooah/pyenv-default-packages).

**Comment by yyuu** [comment]
@jawshooah Cool :+1:  Why would I remove that from Wiki!!

**Comment by jawshooah** [comment]
The wording on the Plugins page seemed to indicate that all plugins listed there must first be approved by maintainers, so I just wanted to make sure you were cool with it :beers:

**Comment by rodfersou** [comment]
Nice! I didn't know about this plugins page! I think this issue could be closed!

Thank you

**Comment by rodfersou** [comment]
@jawshooah maybe we should add support of https://github.com/yyuu/pyenv-virtualenvwrapper too at your plugin

**Comment by jawshooah** [comment]
I haven't used that plugin, but feel free to open an issue on the plugin repo (or better yet, submit a PR!)

**Comment by rodfersou** [comment]
@jawshooah I havent used that plugin either, it was just an idea :smile:
