### ISSUE TITLE
"source activate" causes error in pyenv-which-ext that exits shell

### ISSUE THREAD

**Issue by jimmywan** [yyuu/pyenv-virtualenv#88]
I had a little trouble getting virtualenvwrapper to work properly with conda, but it doesn't sound like that's really a supported configuration by conda, So I tried to use conda envs directly, when this happened.

First setup pyenv version and find activate/conda
```
vagrant@ubuntu-14:~$ PYENV_DEBUG=1
vagrant@ubuntu-14:~$ which activate
/home/vagrant/.pyenv/shims/activate
vagrant@ubuntu-14:~$ less /home/vagrant/.pyenv/shims/activate
vagrant@ubuntu-14:~$ pyenv shell miniconda-3.9.1
vagrant@ubuntu-14:~$ which activate
/home/vagrant/.pyenv/shims/activate
vagrant@ubuntu-14:~$ pyenv which activate
/home/vagrant/.pyenv/versions/miniconda-3.9.1/bin/activate
vagrant@ubuntu-14:~$ which conda
/home/vagrant/.pyenv/shims/conda
vagrant@ubuntu-14:~$ pyenv which conda
/home/vagrant/.pyenv/versions/miniconda-3.9.1/bin/conda
```
So at this point, it looks like I'm correctly using miniconda-3.9.1 and pyenv correctly appears to want to use the activate definition from miniconda-3.9.1.

Next I'll verify that the conda environment is there
```
vagrant@ubuntu-14:~$ conda info --envs
# conda environments:
#
manda                    /home/vagrant/.pyenv/versions/miniconda-3.9.1/envs/manda
root                  *  /home/vagrant/.pyenv/versions/miniconda-3.9.1
```
I've confirmed that conda thinks I have a conda env named "manda"

Now I'll try to activate my environment (http://conda.pydata.org/docs/using/envs.html), but some interactions between conda and the lookup_from_path.bash script causes me to get kicked out of my shell:
```
vagrant@ubuntu-14:~$ source activate manda
++ program=-bash
++ '[' -bash = python ']'
++ export PYENV_ROOT=/home/vagrant/.pyenv
++ PYENV_ROOT=/home/vagrant/.pyenv
++ exec /home/vagrant/.pyenv/libexec/pyenv exec -bash manda
/home/vagrant/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d/which/lookup_from_path.bash: line 38: command: -b: invalid option
command: usage: command [-pVv] command [arg ...]
pyenv: -bash: command not found
Connection to 127.0.0.1 closed.
```

Any ideas?

This is the relevant part of my ~/.profile
``` bash
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export WORKON_HOME=${HOME}/.virtualenvs
export PROJECT_HOME=/cygwin/code
# Disable virtualenvwrapper for now
#pyenv virtualenvwrapper
```

Some relevant environment variables after I set my pyenv version:
```
vagrant@ubuntu-14:~$ env | egrep 'PYENV|PATH'
PYENV_ROOT=/home/vagrant/.pyenv
PYENV_VERSION=miniconda-3.9.1
PYENV_VIRTUALENV_INIT=1
PATH=/home/vagrant/.pyenv/shims:/home/vagrant/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PYENV_SHELL=bash
```

**Comment by yyuu** [comment]
pyenv's _shim_ scripts are not be able to be `source`'d from shell, at least for now. The could of the problem is not relevant to the existence of pyenv-which-ext.

If we need some interactions between pyenv and user's shell, we have to create `pyenv-sh-*` script (e.g. `pyenv-sh-activate`, `pyenv-sh-deactivate`) to inject commands into user's shell. I added some fixes in #91 to allow handling conda's environments as a version of pyenv. This works differently from standard Anaconda/Miniconda, but it would allow you to switch between versions in pyenv way. Please give it a try.

**Comment by yyuu** [comment]
Released pyenv-virtualenv v20150719 with supporting `conda` environments. Please use `pyenv activate ${ENV_NAME}` instead of `source activate ${ENV_NAME}`.

**Comment by jimmywan** [comment]
Thanks! Initial testing seems to indicate that everything is now working as intended so I can also dump pyenv-virtualenvwrapper.
