### ISSUE TITLE
Add a --skip-existing option when creating a virtualenv

### ISSUE THREAD

**Issue by myers** [yyuu/pyenv-virtualenv#90]
I would like `pyenv virtualenv --skip-existing 3.4.3 photos` to skip making the `photos` virutalenv if it already exists, much like `pyenv install --skip-existing 3.4.3` skips installing 3.4.3 if it's installed.

**Comment by yyuu** [comment]
Use `[ -d "$(pyenv root)/versions/3.4.3" ]` instead.

**Comment by rmorshea** [comment]
This solution seems to have gotten a lot of downvotes. Perhaps it's worth reconsidering.

**Comment by EliMor** [comment]
> I would like `pyenv virtualenv --skip-existing 3.4.3 photos` to skip making the `photos` virutalenv if it already exists, much like `pyenv install --skip-existing 3.4.3` skips installing 3.4.3 if it's installed.

I would like this too but a quick hack solution I'm sure everyone is aware of is to just add ``` || true``` to your install at the end....
