### ISSUE TITLE
pyenv-virtualenv with pycharm, error in Django terminal

### ISSUE THREAD

**Issue by musicformellons** [yyuu/pyenv-virtualenv#96]
I am installing this cookiecutter: 
https://github.com/pydanny/cookiecutter-django

I do use pyenv-virtualenv for my virtualenvironment needs: 
https://github.com/yyuu/pyenv-virtualenv

Everything is working fine when I run from the terminal: 
(pyenvVE) ~/projectfolder$ python manage.py runserver

System check identified no issues (0 silenced). 
August 18, 2015 - 14:36:38 
Django version 1.8.3, using settings 'config.settings.local' 
Starting development server at http://127.0.0.1:8000/ 
Quit the server with CONTROL-C.

To work in Pycharm I created the project as I normally do and select the pyenv-virtualenv and add it to .pycharmrc etc. Everything seems fine, I can open the terminal in Pycharm and the virtualenv is already activated and I can do python manage.py runserver from there as well.

However when I do Ctrl+R to start the django-terminal I get the following error which I can not solve (I tried fiddling with the SECRET_KEY settings but to no avail): 
Failed to get real commands on module "cookie": python process died with code 1: Traceback (most recent call last): 
File "/opt/pycharm/helpers/pycharm/_jb_manage_tasks_provider.py", line 20, in <module> 
django.setup() 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/__init__.py", line 17, in setup 
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__ 
self._setup(name) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup 
self._wrapped = Settings(settings_module) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__ 
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.") 
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

The maintainer of the cookiecutter says about this issue:
It appears that pycharm's Django Terminal is trying to access the production.py settings module, instead of local.py. For what it's worth, this has nothing to do with cookiecutter-django. I suspect it has something to do with pyenv-virtualenv combined with pycharm.

**Comment by musicformellons** [comment]
Solved. This appeared to be a bug in Pycharm 4.5.3; it is solved in current version Pycharm 4.5.4

**Comment by bemall** [comment]
This is still an issue with 4.5.4

**Comment by blueyed** [comment]
Re-opening according to previous comment.
@bemall 
Can you provide more information, please?

**Comment by musicformellons** [comment]
When I was under version 4.5.3 Pycharm helpdesk suggested to look in the logs (in your pycharm folder) to see whether there was a record like "at com.jetbrains.django.templateFSLoader.DjangoTemplateFSLoader8.getFolders(DjangoTemplateFSLoader8.java:50)"

This was indeed the case and this issue was solved in version 4.5.4; It definitely worked for me.

Also make sure you have your Django settings in line with this:
![image](https://cloud.githubusercontent.com/assets/10334123/9837793/089014e4-5a4b-11e5-8ae0-804b76f825e0.png)

Django project root being the folder in which manage.py resides.

**Comment by bemall** [comment]
@blueyed  I went through this again and it happens that there are a few places to enter the variables. I was able to resolve by adding these in Pycharm > Preferences > Console > Python Console and Django Console. I had the settings mentioned by @musicformellons already in place. This issue can be closed.
