### ISSUE TITLE
Can't create virtualenv from system python

### ISSUE THREAD

**Issue by oblitum** [yyuu/pyenv-virtualenv#99]
I'm unable to create a virtualenv from system installation, I'm trying to use the `-p` option as I've seen it being used elsewhere for that although I dunno where to get proper docs for this, it worked before but now it stopped working for quite some time already.

```
❯❯❯ pyenv virtualenv -p /usr/local/bin/python foo
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /usr/local/lib/python2.7/site-packages
/usr/local/Cellar/pyenv/HEAD/libexec/pyenv-exec: /usr/local/bin/virtualenv: /usr/local/opt/python3/bin/python3.4: bad interpreter: No such file or directory
/usr/local/Cellar/pyenv/HEAD/libexec/pyenv-exec: line 47: /usr/local/bin/virtualenv: Undefined error: 0
Installing pip from https://bootstrap.pypa.io/get-pip.py...
pyenv: version `foo' is not installed
error: failed to install pip via get-pip.py
```

**Comment by oblitum** [comment]
`pyenv virtualenv -p /usr/local/bin/python foo` tries to install packages locally instead of creating a virtualenv.

**Comment by oblitum** [comment]
Well, for some reason using `pyenv virtualenv -p /usr/local/bin/python2.7 foo` works.

**Comment by PaulRBerg** [comment]
You might want to check out [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv).
